# Primary level word data: one entry per week.

PRIMARY_WORDS = [
    {'week': 1, 'theme': 'Feelings', 'words': [
        {'word': 'cheerful', 'pos': 'adjective', 'meaning': 'Noticeably happy and optimistic.',
         'sentence': 'The cheerful girl waved at everyone she passed.',
         'synonyms': ['happy', 'jolly'], 'antonyms': ['gloomy', 'sad']},
        {'word': 'anxious', 'pos': 'adjective', 'meaning': 'Feeling worried or nervous about something.',
         'sentence': 'He felt anxious before his first swimming lesson.',
         'synonyms': ['worried', 'nervous'], 'antonyms': ['calm', 'relaxed']},
        {'word': 'furious', 'pos': 'adjective', 'meaning': 'Extremely angry.',
         'sentence': 'Mum was furious when the dog chewed her shoes.',
         'synonyms': ['angry', 'livid'], 'antonyms': ['pleased', 'calm']},
        {'word': 'grateful', 'pos': 'adjective', 'meaning': 'Feeling or showing thanks.',
         'sentence': 'We were grateful for the warm soup on a cold day.',
         'synonyms': ['thankful'], 'antonyms': ['ungrateful']},
        {'word': 'lonely', 'pos': 'adjective', 'meaning': 'Sad because one has no friends or company.',
         'sentence': 'The new boy felt lonely on his first day.',
         'synonyms': ['alone', 'isolated'], 'antonyms': ['sociable']},
        {'word': 'excited', 'pos': 'adjective', 'meaning': 'Very happy and full of energy about something that is going to happen.',
         'sentence': 'We were excited about the trip to the zoo.',
         'synonyms': ['thrilled', 'eager'], 'antonyms': ['bored', 'unenthusiastic']},
        {'word': 'nervous', 'pos': 'adjective', 'meaning': 'A little afraid or worried about something.',
         'sentence': 'She felt nervous before reading her poem aloud.',
         'synonyms': ['anxious', 'uneasy'], 'antonyms': ['calm', 'confident']},
        {'word': 'proud', 'pos': 'adjective', 'meaning': 'Feeling pleased about something good you or someone else has done.',
         'sentence': 'Dad was proud of my school report.',
         'synonyms': ['pleased', 'delighted'], 'antonyms': ['ashamed', 'humble']},
        {'word': 'embarrassed', 'pos': 'adjective', 'meaning': 'Feeling shy or awkward in front of other people.',
         'sentence': 'He was embarrassed when he tripped on the stage.',
         'synonyms': ['ashamed', 'awkward'], 'antonyms': ['comfortable', 'confident']},
        {'word': 'disappointed', 'pos': 'adjective', 'meaning': 'Sad because something was not as good as you hoped.',
         'sentence': 'We were disappointed when the picnic was cancelled.',
         'synonyms': ['let down', 'upset'], 'antonyms': ['delighted', 'satisfied']},
    ]},
    {'week': 2, 'theme': 'Nature', 'words': [
        {'word': 'meadow', 'pos': 'noun', 'meaning': 'A field of grass and wild flowers.',
         'sentence': 'Cows grazed quietly in the meadow.',
         'synonyms': ['field', 'pasture'], 'antonyms': []},
        {'word': 'blossom', 'pos': 'noun', 'meaning': 'A flower on a tree or bush.',
         'sentence': 'Pink blossom covered the cherry tree in spring.',
         'synonyms': ['bloom', 'flower'], 'antonyms': []},
        {'word': 'stream', 'pos': 'noun', 'meaning': 'A small, narrow river.',
         'sentence': 'We dipped our toes in the cool stream.',
         'synonyms': ['brook', 'creek'], 'antonyms': []},
        {'word': 'gentle', 'pos': 'adjective', 'meaning': 'Mild, soft or kind.',
         'sentence': 'A gentle breeze rustled the leaves.',
         'synonyms': ['soft', 'mild'], 'antonyms': ['harsh', 'rough']},
        {'word': 'thunder', 'pos': 'noun', 'meaning': 'The loud rumbling noise heard after lightning.',
         'sentence': 'The thunder was so loud that the windows shook.',
         'synonyms': ['rumble'], 'antonyms': []},
        {'word': 'forest', 'pos': 'noun', 'meaning': 'A large area covered with trees.',
         'sentence': 'We followed a path through the forest.',
         'synonyms': ['woods', 'woodland'], 'antonyms': ['desert']},
        {'word': 'pebble', 'pos': 'noun', 'meaning': 'A small, smooth stone.',
         'sentence': 'She skimmed a flat pebble across the pond.',
         'synonyms': ['stone', 'rock'], 'antonyms': ['boulder']},
        {'word': 'petal', 'pos': 'noun', 'meaning': 'One of the coloured parts around the middle of a flower.',
         'sentence': 'A single red petal floated down to the grass.',
         'synonyms': [], 'antonyms': []},
        {'word': 'hedge', 'pos': 'noun', 'meaning': 'A row of bushes growing close together, often as a fence.',
         'sentence': 'A sparrow was hiding in the hedge.',
         'synonyms': ['bushes', 'barrier'], 'antonyms': []},
        {'word': 'valley', 'pos': 'noun', 'meaning': 'A low area of land between hills or mountains.',
         'sentence': 'A river runs through the green valley.',
         'synonyms': ['dale', 'glen'], 'antonyms': ['hill', 'peak']},
    ]},
    {'week': 3, 'theme': 'At School', 'words': [
        {'word': 'library', 'pos': 'noun', 'meaning': 'A room or building where books are kept for reading or borrowing.',
         'sentence': 'She borrowed three books from the library.',
         'synonyms': [], 'antonyms': []},
        {'word': 'explain', 'pos': 'verb', 'meaning': 'To make something clear by describing it.',
         'sentence': 'Can you explain how you solved the puzzle?',
         'synonyms': ['describe', 'clarify'], 'antonyms': ['confuse']},
        {'word': 'practise', 'pos': 'verb', 'meaning': 'To do something again and again to get better at it.',
         'sentence': 'I practise the piano every evening.',
         'synonyms': ['rehearse', 'train'], 'antonyms': []},
        {'word': 'answer', 'pos': 'noun', 'meaning': 'A reply to a question.',
         'sentence': 'He wrote his answer neatly in the box.',
         'synonyms': ['reply', 'response'], 'antonyms': ['question']},
        {'word': 'separate', 'pos': 'adjective', 'meaning': 'Forming a unit by itself; not joined.',
         'sentence': 'Keep the red and blue pencils in separate boxes.',
         'synonyms': ['apart', 'distinct'], 'antonyms': ['joined', 'together']},
        {'word': 'homework', 'pos': 'noun', 'meaning': 'Work that a teacher asks you to do at home.',
         'sentence': 'I finish my homework before dinner.',
         'synonyms': [], 'antonyms': []},
        {'word': 'classroom', 'pos': 'noun', 'meaning': 'A room where a class of pupils is taught.',
         'sentence': 'Our classroom has a big window.',
         'synonyms': [], 'antonyms': []},
        {'word': 'lesson', 'pos': 'noun', 'meaning': 'A period of time when a teacher teaches something.',
         'sentence': 'The maths lesson was about fractions.',
         'synonyms': ['class', 'session'], 'antonyms': []},
        {'word': 'project', 'pos': 'noun', 'meaning': 'A piece of work that is planned and finished over a period of time.',
         'sentence': 'Our class project is about volcanoes.',
         'synonyms': ['task', 'assignment'], 'antonyms': []},
        {'word': 'assembly', 'pos': 'noun', 'meaning': 'A gathering of the whole school to hear news or songs.',
         'sentence': 'The head teacher spoke at assembly this morning.',
         'synonyms': ['gathering', 'meeting'], 'antonyms': []},
    ]},
    {'week': 4, 'theme': 'Animals', 'words': [
        {'word': 'kangaroo', 'pos': 'noun', 'meaning': 'An Australian animal that hops on strong back legs and carries its baby in a pouch.',
         'sentence': 'The kangaroo bounded across the field.',
         'synonyms': [], 'antonyms': []},
        {'word': 'predator', 'pos': 'noun', 'meaning': 'An animal that hunts other animals for food.',
         'sentence': 'The owl is a night-time predator.',
         'synonyms': ['hunter'], 'antonyms': ['prey']},
        {'word': 'hibernate', 'pos': 'verb', 'meaning': 'To spend the winter in a deep sleep.',
         'sentence': 'Bears hibernate in caves until spring.',
         'synonyms': ['sleep through winter'], 'antonyms': []},
        {'word': 'nocturnal', 'pos': 'adjective', 'meaning': 'Active at night rather than during the day.',
         'sentence': 'Bats are nocturnal animals.',
         'synonyms': ['night-time'], 'antonyms': ['diurnal', 'daytime']},
        {'word': 'habitat', 'pos': 'noun', 'meaning': 'The natural home of an animal or plant.',
         'sentence': 'The pond is the perfect habitat for frogs.',
         'synonyms': ['home', 'environment'], 'antonyms': []},
        {'word': 'herd', 'pos': 'noun', 'meaning': 'A large group of animals of the same kind that live together.',
         'sentence': 'A herd of elephants walked to the river.',
         'synonyms': ['flock', 'pack'], 'antonyms': []},
        {'word': 'camouflage', 'pos': 'noun', 'meaning': 'Colours or patterns that help an animal blend in with its surroundings.',
         'sentence': 'The chameleon uses camouflage to hide on a leaf.',
         'synonyms': ['disguise'], 'antonyms': []},
        {'word': 'migrate', 'pos': 'verb', 'meaning': 'To travel to another place at a certain time of year.',
         'sentence': 'Swallows migrate to warmer lands for the winter.',
         'synonyms': ['travel', 'relocate'], 'antonyms': ['stay']},
        {'word': 'tortoise', 'pos': 'noun', 'meaning': 'A slow-moving reptile with a hard shell.',
         'sentence': 'The tortoise slowly munched a lettuce leaf.',
         'synonyms': [], 'antonyms': []},
        {'word': 'mammal', 'pos': 'noun', 'meaning': 'A warm-blooded animal that feeds its babies with milk.',
         'sentence': 'A whale is a mammal, not a fish.',
         'synonyms': [], 'antonyms': []},
    ]},
    {'week': 5, 'theme': 'Food and Cooking', 'words': [
        {'word': 'ingredient', 'pos': 'noun', 'meaning': 'One of the foods that you mix together to make a dish.',
         'sentence': 'Flour is the main ingredient in bread.',
         'synonyms': ['component'], 'antonyms': []},
        {'word': 'recipe', 'pos': 'noun', 'meaning': 'A set of instructions for cooking a particular dish.',
         'sentence': 'Grandma gave me her recipe for apple crumble.',
         'synonyms': ['instructions'], 'antonyms': []},
        {'word': 'delicious', 'pos': 'adjective', 'meaning': 'Tasting or smelling very good.',
         'sentence': 'The soup was warm and delicious.',
         'synonyms': ['tasty', 'yummy'], 'antonyms': ['disgusting', 'bland']},
        {'word': 'stir', 'pos': 'verb', 'meaning': 'To mix a liquid or food by moving a spoon around in it.',
         'sentence': 'Stir the sauce so that it does not stick.',
         'synonyms': ['mix', 'blend'], 'antonyms': []},
        {'word': 'slice', 'pos': 'verb', 'meaning': 'To cut something into thin, flat pieces.',
         'sentence': 'Please slice the bread for the sandwiches.',
         'synonyms': ['cut', 'carve'], 'antonyms': []},
        {'word': 'knead', 'pos': 'verb', 'meaning': 'To press and fold dough with your hands to make it smooth.',
         'sentence': 'You need to knead the dough for ten minutes.',
         'synonyms': ['squeeze', 'work'], 'antonyms': []},
        {'word': 'simmer', 'pos': 'verb', 'meaning': 'To cook gently in liquid that is almost, but not quite, boiling.',
         'sentence': 'Let the soup simmer on a low heat.',
         'synonyms': ['stew'], 'antonyms': ['boil']},
        {'word': 'spicy', 'pos': 'adjective', 'meaning': 'Having a strong, hot taste from spices.',
         'sentence': 'The curry was too spicy for my little sister.',
         'synonyms': ['hot', 'fiery'], 'antonyms': ['mild', 'bland']},
        {'word': 'crunchy', 'pos': 'adjective', 'meaning': 'Firm and making a loud noise when you bite it.',
         'sentence': 'I love the crunchy apples from our tree.',
         'synonyms': ['crisp'], 'antonyms': ['soft', 'soggy']},
        {'word': 'chop', 'pos': 'verb', 'meaning': 'To cut something into small pieces with a knife.',
         'sentence': 'Dad will chop the onions for the stew.',
         'synonyms': ['cut', 'dice'], 'antonyms': []},
    ]},
    {'week': 6, 'theme': 'Weather', 'words': [
        {'word': 'drizzle', 'pos': 'noun', 'meaning': 'Light, fine rain.',
         'sentence': 'A soft drizzle fell on the playground.',
         'synonyms': ['light rain'], 'antonyms': ['downpour']},
        {'word': 'forecast', 'pos': 'noun', 'meaning': 'A report that says what the weather will probably be like.',
         'sentence': 'The forecast says it will be sunny tomorrow.',
         'synonyms': ['prediction'], 'antonyms': []},
        {'word': 'humid', 'pos': 'adjective', 'meaning': 'Warm and damp, so the air feels sticky.',
         'sentence': 'It was hot and humid in the greenhouse.',
         'synonyms': ['muggy', 'damp'], 'antonyms': ['dry']},
        {'word': 'frost', 'pos': 'noun', 'meaning': 'A thin layer of ice crystals that forms on things when it is very cold.',
         'sentence': 'Frost sparkled on the grass this morning.',
         'synonyms': ['ice'], 'antonyms': []},
        {'word': 'rainbow', 'pos': 'noun', 'meaning': 'An arch of colours in the sky when sun shines through rain.',
         'sentence': 'We spotted a rainbow after the shower.',
         'synonyms': [], 'antonyms': []},
        {'word': 'lightning', 'pos': 'noun', 'meaning': 'A bright flash of light in the sky during a storm.',
         'sentence': 'We counted the seconds after the lightning flashed.',
         'synonyms': [], 'antonyms': []},
        {'word': 'fog', 'pos': 'noun', 'meaning': 'Thick cloud close to the ground that makes it hard to see.',
         'sentence': 'The fog was so thick we could not see the gate.',
         'synonyms': ['mist'], 'antonyms': []},
        {'word': 'puddle', 'pos': 'noun', 'meaning': 'A small pool of water on the ground.',
         'sentence': 'He jumped in every puddle on the way home.',
         'synonyms': ['pool'], 'antonyms': []},
        {'word': 'gust', 'pos': 'noun', 'meaning': 'A short, strong rush of wind.',
         'sentence': 'A sudden gust blew my hat off.',
         'synonyms': ['blast'], 'antonyms': []},
        {'word': 'shower', 'pos': 'noun', 'meaning': 'A short fall of rain.',
         'sentence': 'We sheltered under a tree during the shower.',
         'synonyms': ['sprinkle'], 'antonyms': []},
    ]},
    {'week': 7, 'theme': 'Sports and Games', 'words': [
        {'word': 'referee', 'pos': 'noun', 'meaning': 'The person who makes sure players follow the rules in a match.',
         'sentence': 'The referee blew the whistle for half-time.',
         'synonyms': ['umpire', 'official'], 'antonyms': []},
        {'word': 'tournament', 'pos': 'noun', 'meaning': 'A competition in which many players or teams play against each other.',
         'sentence': 'Our school won the football tournament.',
         'synonyms': ['competition'], 'antonyms': []},
        {'word': 'champion', 'pos': 'noun', 'meaning': 'The winner of a competition.',
         'sentence': 'She became the swimming champion of the county.',
         'synonyms': ['winner'], 'antonyms': ['loser']},
        {'word': 'goalkeeper', 'pos': 'noun', 'meaning': 'The player whose job is to stop the ball going into the goal.',
         'sentence': 'The goalkeeper dived and saved the shot.',
         'synonyms': ['goalie'], 'antonyms': []},
        {'word': 'stadium', 'pos': 'noun', 'meaning': 'A large building with seats around a sports field.',
         'sentence': 'Thousands of fans filled the stadium.',
         'synonyms': ['arena'], 'antonyms': []},
        {'word': 'opponent', 'pos': 'noun', 'meaning': 'A person or team that you play against.',
         'sentence': 'Our opponent was very friendly after the game.',
         'synonyms': ['rival', 'competitor'], 'antonyms': ['teammate', 'partner']},
        {'word': 'defend', 'pos': 'verb', 'meaning': 'To protect a goal or position from being attacked in a game.',
         'sentence': 'The players worked hard to defend their goal.',
         'synonyms': ['protect', 'guard'], 'antonyms': ['attack']},
        {'word': 'tackle', 'pos': 'verb', 'meaning': 'To try to take the ball from another player.',
         'sentence': 'He managed to tackle the striker fairly.',
         'synonyms': ['challenge'], 'antonyms': []},
        {'word': 'relay', 'pos': 'noun', 'meaning': 'A race in which team members take turns to run part of the distance.',
         'sentence': 'Our team came second in the relay.',
         'synonyms': [], 'antonyms': []},
        {'word': 'trophy', 'pos': 'noun', 'meaning': 'A cup or prize given to the winner of a competition.',
         'sentence': 'The captain lifted the shiny trophy.',
         'synonyms': ['cup', 'prize'], 'antonyms': []},
    ]},
    {'week': 8, 'theme': 'Family and Friends', 'words': [
        {'word': 'cousin', 'pos': 'noun', 'meaning': 'The child of your aunt or uncle.',
         'sentence': 'My cousin is staying with us for the holidays.',
         'synonyms': [], 'antonyms': []},
        {'word': 'grandparent', 'pos': 'noun', 'meaning': 'The mother or father of your mum or dad.',
         'sentence': 'Each grandparent came to my birthday party.',
         'synonyms': [], 'antonyms': []},
        {'word': 'sibling', 'pos': 'noun', 'meaning': 'A brother or sister.',
         'sentence': 'I share a bedroom with my younger sibling.',
         'synonyms': ['brother', 'sister'], 'antonyms': []},
        {'word': 'twins', 'pos': 'noun', 'meaning': 'Two children born to the same mother at the same time.',
         'sentence': 'The twins wear matching coats.',
         'synonyms': [], 'antonyms': []},
        {'word': 'loyal', 'pos': 'adjective', 'meaning': 'Always faithful and supportive to a friend or group.',
         'sentence': 'A loyal friend always sticks up for you.',
         'synonyms': ['faithful', 'devoted'], 'antonyms': ['disloyal', 'unfaithful']},
        {'word': 'trust', 'pos': 'verb', 'meaning': 'To believe that someone is honest and will not let you down.',
         'sentence': 'I trust my best friend with all my secrets.',
         'synonyms': ['rely on', 'believe'], 'antonyms': ['distrust', 'doubt']},
        {'word': 'share', 'pos': 'verb', 'meaning': 'To let someone else have or use part of what you have.',
         'sentence': 'Please share your crayons with Mia.',
         'synonyms': ['divide'], 'antonyms': ['keep']},
        {'word': 'hug', 'pos': 'noun', 'meaning': 'An act of holding someone close in your arms to show you care.',
         'sentence': 'Gran gave me a big hug at the door.',
         'synonyms': ['cuddle', 'embrace'], 'antonyms': []},
        {'word': 'invite', 'pos': 'verb', 'meaning': 'To ask someone to come to a party or event.',
         'sentence': 'I will invite all my class to my party.',
         'synonyms': ['ask'], 'antonyms': []},
        {'word': 'reunion', 'pos': 'noun', 'meaning': 'A meeting of people who have not seen each other for a long time.',
         'sentence': 'The whole family came to the reunion.',
         'synonyms': ['get-together'], 'antonyms': []},
    ]},
    {'week': 9, 'theme': 'The Ocean', 'words': [
        {'word': 'dolphin', 'pos': 'noun', 'meaning': 'A friendly, clever sea mammal with a long beak-like nose.',
         'sentence': 'A dolphin leapt out of the waves beside the boat.',
         'synonyms': [], 'antonyms': []},
        {'word': 'coral', 'pos': 'noun', 'meaning': 'A hard, colourful substance made by tiny sea animals, forming reefs.',
         'sentence': 'Bright fish swam around the coral.',
         'synonyms': [], 'antonyms': []},
        {'word': 'tide', 'pos': 'noun', 'meaning': 'The regular rising and falling of the sea.',
         'sentence': 'The tide came in and washed away our sandcastle.',
         'synonyms': [], 'antonyms': []},
        {'word': 'current', 'pos': 'noun', 'meaning': 'A steady flow of water in one direction.',
         'sentence': 'The strong current carried the boat along.',
         'synonyms': ['flow', 'stream'], 'antonyms': []},
        {'word': 'octopus', 'pos': 'noun', 'meaning': 'A sea creature with a soft body and eight arms.',
         'sentence': 'The octopus squeezed into a tiny cave.',
         'synonyms': [], 'antonyms': []},
        {'word': 'jellyfish', 'pos': 'noun', 'meaning': 'A soft, see-through sea animal that can sting.',
         'sentence': 'We saw a jellyfish floating near the pier.',
         'synonyms': [], 'antonyms': []},
        {'word': 'shore', 'pos': 'noun', 'meaning': 'The land along the edge of the sea.',
         'sentence': 'We collected shells along the shore.',
         'synonyms': ['coast', 'beach'], 'antonyms': []},
        {'word': 'wave', 'pos': 'noun', 'meaning': 'A moving line of water on the surface of the sea.',
         'sentence': 'A big wave splashed over our feet.',
         'synonyms': ['breaker'], 'antonyms': []},
        {'word': 'seaweed', 'pos': 'noun', 'meaning': 'A plant that grows in the sea.',
         'sentence': 'Green seaweed was tangled on the rocks.',
         'synonyms': [], 'antonyms': []},
        {'word': 'submarine', 'pos': 'noun', 'meaning': 'A ship that can travel underwater.',
         'sentence': 'The submarine dived deep beneath the waves.',
         'synonyms': [], 'antonyms': []},
    ]},
    {'week': 10, 'theme': 'Space', 'words': [
        {'word': 'planet', 'pos': 'noun', 'meaning': 'A large round object that moves around a star.',
         'sentence': 'Earth is the planet we live on.',
         'synonyms': ['world'], 'antonyms': []},
        {'word': 'astronaut', 'pos': 'noun', 'meaning': 'A person trained to travel in space.',
         'sentence': 'The astronaut waved from the space station.',
         'synonyms': ['spaceman'], 'antonyms': []},
        {'word': 'galaxy', 'pos': 'noun', 'meaning': 'A huge group of stars, gas and dust.',
         'sentence': 'Our galaxy is called the Milky Way.',
         'synonyms': [], 'antonyms': []},
        {'word': 'orbit', 'pos': 'verb', 'meaning': 'To travel around a planet or star in a curved path.',
         'sentence': 'The Moon takes about a month to orbit the Earth.',
         'synonyms': ['circle'], 'antonyms': []},
        {'word': 'rocket', 'pos': 'noun', 'meaning': 'A tube-shaped vehicle that travels into space.',
         'sentence': 'The rocket blasted off at dawn.',
         'synonyms': ['spacecraft'], 'antonyms': []},
        {'word': 'comet', 'pos': 'noun', 'meaning': 'A ball of ice and dust with a glowing tail that moves around the Sun.',
         'sentence': 'We watched the comet streak across the sky.',
         'synonyms': [], 'antonyms': []},
        {'word': 'telescope', 'pos': 'noun', 'meaning': 'A tool that makes faraway things look bigger and closer.',
         'sentence': 'I looked at the Moon through a telescope.',
         'synonyms': [], 'antonyms': []},
        {'word': 'asteroid', 'pos': 'noun', 'meaning': 'A small rocky object that moves around the Sun.',
         'sentence': 'An asteroid is much smaller than a planet.',
         'synonyms': [], 'antonyms': []},
        {'word': 'gravity', 'pos': 'noun', 'meaning': 'The force that pulls things towards the ground.',
         'sentence': 'Gravity makes an apple fall from a tree.',
         'synonyms': [], 'antonyms': []},
        {'word': 'crater', 'pos': 'noun', 'meaning': 'A large, bowl-shaped hole in the ground or on a planet or moon.',
         'sentence': 'The Moon has a huge crater near its south pole.',
         'synonyms': ['hollow'], 'antonyms': []},
    ]},
    {'week': 11, 'theme': 'Music', 'words': [
        {'word': 'rhythm', 'pos': 'noun', 'meaning': 'A regular pattern of beats in music.',
         'sentence': 'We clapped to the rhythm of the song.',
         'synonyms': ['beat', 'pulse'], 'antonyms': []},
        {'word': 'melody', 'pos': 'noun', 'meaning': 'A tune; a pleasing series of musical notes.',
         'sentence': 'She hummed a happy melody.',
         'synonyms': ['tune'], 'antonyms': []},
        {'word': 'orchestra', 'pos': 'noun', 'meaning': 'A large group of musicians who play together.',
         'sentence': 'The orchestra played loudly at the end.',
         'synonyms': [], 'antonyms': []},
        {'word': 'instrument', 'pos': 'noun', 'meaning': 'An object used for making music, such as a violin.',
         'sentence': 'The flute is my favourite instrument.',
         'synonyms': [], 'antonyms': []},
        {'word': 'choir', 'pos': 'noun', 'meaning': 'A group of people who sing together.',
         'sentence': 'Our school choir sang at the festival.',
         'synonyms': ['chorus'], 'antonyms': []},
        {'word': 'guitar', 'pos': 'noun', 'meaning': 'A musical instrument with strings that you pluck or strum.',
         'sentence': 'He learned to strum a guitar.',
         'synonyms': [], 'antonyms': []},
        {'word': 'drum', 'pos': 'noun', 'meaning': 'A musical instrument you hit with sticks or your hands.',
         'sentence': 'She beat the drum in time with the band.',
         'synonyms': [], 'antonyms': []},
        {'word': 'harmony', 'pos': 'noun', 'meaning': 'Musical notes sounding pleasantly together.',
         'sentence': 'The singers made beautiful harmony.',
         'synonyms': [], 'antonyms': ['discord']},
        {'word': 'concert', 'pos': 'noun', 'meaning': 'A live musical show for an audience.',
         'sentence': 'We went to a concert in the park.',
         'synonyms': ['performance'], 'antonyms': []},
        {'word': 'composer', 'pos': 'noun', 'meaning': 'A person who writes music.',
         'sentence': 'The composer wrote a song for the school.',
         'synonyms': ['songwriter'], 'antonyms': []},
    ]},
    {'week': 12, 'theme': 'Travel and Transport', 'words': [
        {'word': 'passport', 'pos': 'noun', 'meaning': 'An official book that lets you travel to other countries.',
         'sentence': 'Remember to pack your passport.',
         'synonyms': [], 'antonyms': []},
        {'word': 'journey', 'pos': 'noun', 'meaning': 'The act of travelling from one place to another.',
         'sentence': 'The journey to the seaside took three hours.',
         'synonyms': ['trip', 'voyage'], 'antonyms': []},
        {'word': 'luggage', 'pos': 'noun', 'meaning': 'Bags and suitcases that you take on a trip.',
         'sentence': 'We carried our luggage to the train.',
         'synonyms': ['baggage'], 'antonyms': []},
        {'word': 'platform', 'pos': 'noun', 'meaning': 'The raised area at a station where you get on a train.',
         'sentence': 'We waited on the platform for the train.',
         'synonyms': [], 'antonyms': []},
        {'word': 'airport', 'pos': 'noun', 'meaning': 'A place where aeroplanes take off and land.',
         'sentence': 'The airport was busy with holidaymakers.',
         'synonyms': [], 'antonyms': []},
        {'word': 'ticket', 'pos': 'noun', 'meaning': 'A piece of paper that shows you have paid to travel.',
         'sentence': 'I showed my ticket to the bus driver.',
         'synonyms': ['pass'], 'antonyms': []},
        {'word': 'voyage', 'pos': 'noun', 'meaning': 'A long journey by sea or in space.',
         'sentence': 'The voyage across the ocean took a week.',
         'synonyms': ['journey', 'cruise'], 'antonyms': []},
        {'word': 'tram', 'pos': 'noun', 'meaning': 'A passenger vehicle that runs on rails along a street.',
         'sentence': 'We rode the tram into town.',
         'synonyms': [], 'antonyms': []},
        {'word': 'tunnel', 'pos': 'noun', 'meaning': 'A passage built under the ground or through a hill.',
         'sentence': 'The train rushed into the tunnel.',
         'synonyms': [], 'antonyms': []},
        {'word': 'ferry', 'pos': 'noun', 'meaning': 'A boat that carries people and vehicles across water.',
         'sentence': 'We took the ferry to the island.',
         'synonyms': [], 'antonyms': []},
    ]},
    {'week': 13, 'theme': 'Healthy Bodies', 'words': [
        {'word': 'muscle', 'pos': 'noun', 'meaning': 'A part of the body that tightens to make you move.',
         'sentence': 'Running makes your leg muscle stronger.',
         'synonyms': [], 'antonyms': []},
        {'word': 'skeleton', 'pos': 'noun', 'meaning': 'The frame of bones inside your body.',
         'sentence': 'A skeleton holds your body up.',
         'synonyms': [], 'antonyms': []},
        {'word': 'bones', 'pos': 'noun', 'meaning': 'The hard parts that make up your skeleton.',
         'sentence': 'Milk helps to keep your bones strong.',
         'synonyms': [], 'antonyms': []},
        {'word': 'heart', 'pos': 'noun', 'meaning': 'The organ in your chest that pumps blood around your body.',
         'sentence': 'Your heart beats faster when you run.',
         'synonyms': [], 'antonyms': []},
        {'word': 'lungs', 'pos': 'noun', 'meaning': 'The organs in your chest that you use to breathe.',
         'sentence': 'Your lungs fill with air when you breathe in.',
         'synonyms': [], 'antonyms': []},
        {'word': 'exercise', 'pos': 'noun', 'meaning': 'Physical activity that keeps your body fit.',
         'sentence': 'Daily exercise keeps us healthy.',
         'synonyms': ['activity', 'workout'], 'antonyms': ['rest']},
        {'word': 'vitamin', 'pos': 'noun', 'meaning': 'A substance in food that your body needs to stay healthy.',
         'sentence': 'Oranges are full of vitamin C.',
         'synonyms': [], 'antonyms': []},
        {'word': 'energy', 'pos': 'noun', 'meaning': 'The strength to be active without getting tired.',
         'sentence': 'Breakfast gives me energy for the morning.',
         'synonyms': ['strength', 'vigour'], 'antonyms': ['tiredness']},
        {'word': 'breathe', 'pos': 'verb', 'meaning': 'To take air into your lungs and let it out again.',
         'sentence': 'Breathe in slowly through your nose.',
         'synonyms': ['inhale', 'exhale'], 'antonyms': []},
        {'word': 'stretch', 'pos': 'verb', 'meaning': 'To reach out or make your body longer.',
         'sentence': 'We stretch our arms before every game.',
         'synonyms': ['extend', 'reach'], 'antonyms': ['bend']},
    ]},
    {'week': 14, 'theme': 'Inventions', 'words': [
        {'word': 'invent', 'pos': 'verb', 'meaning': 'To make or think of something completely new.',
         'sentence': 'Who was the first to invent the bicycle?',
         'synonyms': ['create', 'devise'], 'antonyms': ['copy']},
        {'word': 'machine', 'pos': 'noun', 'meaning': 'A tool with moving parts that does a job.',
         'sentence': 'A washing machine cleans our clothes.',
         'synonyms': ['device', 'engine'], 'antonyms': []},
        {'word': 'electricity', 'pos': 'noun', 'meaning': 'A form of energy that powers lights and machines.',
         'sentence': 'Electricity makes the lamp glow.',
         'synonyms': ['power'], 'antonyms': []},
        {'word': 'engine', 'pos': 'noun', 'meaning': 'A machine that turns fuel into movement.',
         'sentence': 'The engine roared as the car started.',
         'synonyms': ['motor'], 'antonyms': []},
        {'word': 'telephone', 'pos': 'noun', 'meaning': 'A device used to talk to someone far away.',
         'sentence': 'Alexander Graham Bell is known for the telephone.',
         'synonyms': ['phone'], 'antonyms': []},
        {'word': 'device', 'pos': 'noun', 'meaning': 'A small tool or machine made for a special job.',
         'sentence': 'This device counts how many steps you take.',
         'synonyms': ['gadget', 'tool'], 'antonyms': []},
        {'word': 'wheel', 'pos': 'noun', 'meaning': 'A round object that turns to help things move.',
         'sentence': 'The wheel was one of the most important inventions.',
         'synonyms': [], 'antonyms': []},
        {'word': 'battery', 'pos': 'noun', 'meaning': 'A small container that stores electricity.',
         'sentence': 'The torch needs a new battery.',
         'synonyms': [], 'antonyms': []},
        {'word': 'camera', 'pos': 'noun', 'meaning': 'A device for taking photographs.',
         'sentence': 'She took a photo with her new camera.',
         'synonyms': [], 'antonyms': []},
        {'word': 'printer', 'pos': 'noun', 'meaning': 'A machine that puts words or pictures onto paper.',
         'sentence': 'The printer ran out of ink.',
         'synonyms': [], 'antonyms': []},
    ]},
    {'week': 15, 'theme': 'Festivals and Celebrations', 'words': [
        {'word': 'celebrate', 'pos': 'verb', 'meaning': 'To do something special to mark a happy day.',
         'sentence': 'We celebrate my birthday with a cake.',
         'synonyms': ['party', 'rejoice'], 'antonyms': ['mourn']},
        {'word': 'lantern', 'pos': 'noun', 'meaning': 'A light with a case around it so the flame or bulb is protected.',
         'sentence': 'Each child carried a glowing lantern in the parade.',
         'synonyms': ['lamp'], 'antonyms': []},
        {'word': 'firework', 'pos': 'noun', 'meaning': 'A device that makes bright lights and bangs in the sky.',
         'sentence': 'Each firework lit up the night sky.',
         'synonyms': [], 'antonyms': []},
        {'word': 'parade', 'pos': 'noun', 'meaning': 'A line of people, floats or bands moving along a street.',
         'sentence': 'The parade marched past our house.',
         'synonyms': ['procession'], 'antonyms': []},
        {'word': 'costume', 'pos': 'noun', 'meaning': 'Special clothes worn for a party or a play.',
         'sentence': 'I wore a pirate costume to the party.',
         'synonyms': ['outfit'], 'antonyms': []},
        {'word': 'feast', 'pos': 'noun', 'meaning': 'A large and special meal.',
         'sentence': 'The family sat down to a feast.',
         'synonyms': ['banquet'], 'antonyms': []},
        {'word': 'tradition', 'pos': 'noun', 'meaning': 'A custom that has been passed down over many years.',
         'sentence': 'It is a tradition to hang stockings at Christmas.',
         'synonyms': ['custom'], 'antonyms': []},
        {'word': 'decoration', 'pos': 'noun', 'meaning': 'Something added to make a place look nicer.',
         'sentence': 'Each decoration was shiny and gold.',
         'synonyms': ['ornament'], 'antonyms': []},
        {'word': 'carnival', 'pos': 'noun', 'meaning': 'A lively festival with music, costumes and dancing in the streets.',
         'sentence': 'The carnival filled the town with music.',
         'synonyms': ['festival'], 'antonyms': []},
        {'word': 'gift', 'pos': 'noun', 'meaning': 'Something given to someone as a present.',
         'sentence': 'She wrapped a gift for her friend.',
         'synonyms': ['present'], 'antonyms': []},
    ]},
    {'week': 16, 'theme': 'Books and Stories', 'words': [
        {'word': 'author', 'pos': 'noun', 'meaning': 'A person who writes a book.',
         'sentence': 'The author signed copies of her book.',
         'synonyms': ['writer'], 'antonyms': []},
        {'word': 'chapter', 'pos': 'noun', 'meaning': 'One of the parts that a book is divided into.',
         'sentence': 'I read one chapter before bed.',
         'synonyms': ['section'], 'antonyms': []},
        {'word': 'character', 'pos': 'noun', 'meaning': 'A person or animal in a story.',
         'sentence': 'My favourite character is the brave mouse.',
         'synonyms': [], 'antonyms': []},
        {'word': 'illustrate', 'pos': 'verb', 'meaning': 'To draw pictures for a book.',
         'sentence': 'She was asked to illustrate the story.',
         'synonyms': ['draw'], 'antonyms': []},
        {'word': 'plot', 'pos': 'noun', 'meaning': 'The main events that happen in a story.',
         'sentence': 'The plot had a surprising twist.',
         'synonyms': ['storyline'], 'antonyms': []},
        {'word': 'fiction', 'pos': 'noun', 'meaning': 'Stories that are made up and not real.',
         'sentence': 'I enjoy reading fiction about animals.',
         'synonyms': ['fantasy'], 'antonyms': ['fact']},
        {'word': 'title', 'pos': 'noun', 'meaning': 'The name of a book, poem or film.',
         'sentence': 'The title of the book is on the cover.',
         'synonyms': ['name'], 'antonyms': []},
        {'word': 'sequel', 'pos': 'noun', 'meaning': 'A book or film that continues the story of an earlier one.',
         'sentence': 'I cannot wait for the sequel to come out.',
         'synonyms': ['follow-up'], 'antonyms': []},
        {'word': 'narrator', 'pos': 'noun', 'meaning': 'The person who tells the story.',
         'sentence': 'The narrator of the story is a young girl.',
         'synonyms': ['storyteller'], 'antonyms': []},
        {'word': 'poem', 'pos': 'noun', 'meaning': 'A piece of writing arranged in lines, often with rhyme.',
         'sentence': 'We learned a poem about autumn.',
         'synonyms': ['verse'], 'antonyms': []},
    ]},
    {'week': 17, 'theme': 'Dinosaurs', 'words': [
        {'word': 'fossil', 'pos': 'noun', 'meaning': 'The remains of a plant or animal that has turned into stone over millions of years.',
         'sentence': 'We found a fossil of a shell.',
         'synonyms': ['remains'], 'antonyms': []},
        {'word': 'extinct', 'pos': 'adjective', 'meaning': 'No longer alive anywhere on Earth.',
         'sentence': 'Dinosaurs became extinct millions of years ago.',
         'synonyms': ['died out'], 'antonyms': ['alive', 'living']},
        {'word': 'herbivore', 'pos': 'noun', 'meaning': 'An animal that eats only plants.',
         'sentence': 'A Triceratops was a herbivore.',
         'synonyms': ['plant-eater'], 'antonyms': ['carnivore']},
        {'word': 'carnivore', 'pos': 'noun', 'meaning': 'An animal that eats meat.',
         'sentence': 'A Tyrannosaurus rex was a huge carnivore.',
         'synonyms': ['meat-eater'], 'antonyms': ['herbivore']},
        {'word': 'reptile', 'pos': 'noun', 'meaning': 'A cold-blooded animal with scaly skin, like a lizard.',
         'sentence': 'Many dinosaurs were a type of reptile.',
         'synonyms': [], 'antonyms': []},
        {'word': 'prehistoric', 'pos': 'adjective', 'meaning': 'From the time before history was written down.',
         'sentence': 'We saw prehistoric footprints in a museum.',
         'synonyms': ['ancient'], 'antonyms': ['modern']},
        {'word': 'giant', 'pos': 'adjective', 'meaning': 'Extremely large.',
         'sentence': 'A giant dinosaur once walked here.',
         'synonyms': ['huge', 'enormous'], 'antonyms': ['tiny']},
        {'word': 'scales', 'pos': 'noun', 'meaning': 'Small, hard, flat plates that cover the skin of some animals.',
         'sentence': 'The lizard has shiny green scales.',
         'synonyms': [], 'antonyms': []},
        {'word': 'claw', 'pos': 'noun', 'meaning': 'A sharp, curved nail on an animal\'s foot.',
         'sentence': 'The dinosaur had a long claw on each toe.',
         'synonyms': ['talon'], 'antonyms': []},
        {'word': 'tail', 'pos': 'noun', 'meaning': 'The part that sticks out from the back of an animal.',
         'sentence': 'The dinosaur\'s long tail swished behind it.',
         'synonyms': [], 'antonyms': []},
    ]},
    {'week': 18, 'theme': 'In the City', 'words': [
        {'word': 'traffic', 'pos': 'noun', 'meaning': 'Cars, buses and other vehicles on the road.',
         'sentence': 'The traffic was slow in the rain.',
         'synonyms': [], 'antonyms': []},
        {'word': 'skyscraper', 'pos': 'noun', 'meaning': 'A very tall building.',
         'sentence': 'The skyscraper towered above the city.',
         'synonyms': ['tower'], 'antonyms': []},
        {'word': 'pavement', 'pos': 'noun', 'meaning': 'The path at the side of a road for people to walk on.',
         'sentence': 'Please walk on the pavement.',
         'synonyms': ['footpath'], 'antonyms': []},
        {'word': 'crossing', 'pos': 'noun', 'meaning': 'A place where people can cross the road safely.',
         'sentence': 'Wait at the crossing until the green man shows.',
         'synonyms': [], 'antonyms': []},
        {'word': 'market', 'pos': 'noun', 'meaning': 'A place where people buy and sell things, often outdoors.',
         'sentence': 'We bought fresh bread at the market.',
         'synonyms': ['bazaar'], 'antonyms': []},
        {'word': 'bridge', 'pos': 'noun', 'meaning': 'A structure that carries a road or path over water or a road.',
         'sentence': 'We walked over the bridge.',
         'synonyms': [], 'antonyms': []},
        {'word': 'station', 'pos': 'noun', 'meaning': 'A place where trains or buses stop for passengers.',
         'sentence': 'We met Grandpa at the station.',
         'synonyms': [], 'antonyms': []},
        {'word': 'crowd', 'pos': 'noun', 'meaning': 'A large group of people together in one place.',
         'sentence': 'A crowd gathered to watch the street dancers.',
         'synonyms': ['throng'], 'antonyms': []},
        {'word': 'noisy', 'pos': 'adjective', 'meaning': 'Making a lot of sound.',
         'sentence': 'The city streets are noisy at rush hour.',
         'synonyms': ['loud'], 'antonyms': ['quiet', 'silent']},
        {'word': 'busy', 'pos': 'adjective', 'meaning': 'Full of people or things happening.',
         'sentence': 'The shopping centre was busy on Saturday.',
         'synonyms': ['crowded'], 'antonyms': ['quiet', 'empty']},
    ]},
    {'week': 19, 'theme': 'Farm Life', 'words': [
        {'word': 'harvest', 'pos': 'noun', 'meaning': 'The time when crops are picked; also the crops themselves.',
         'sentence': 'The harvest was ready in September.',
         'synonyms': ['crop'], 'antonyms': []},
        {'word': 'tractor', 'pos': 'noun', 'meaning': 'A strong vehicle used on a farm for pulling heavy machinery.',
         'sentence': 'The farmer drove the tractor across the field.',
         'synonyms': [], 'antonyms': []},
        {'word': 'barn', 'pos': 'noun', 'meaning': 'A large farm building used for storing hay or sheltering animals.',
         'sentence': 'The hay is stored in the barn.',
         'synonyms': [], 'antonyms': []},
        {'word': 'livestock', 'pos': 'noun', 'meaning': 'Farm animals such as cows, sheep and pigs.',
         'sentence': 'The livestock were fed every morning.',
         'synonyms': [], 'antonyms': []},
        {'word': 'crops', 'pos': 'noun', 'meaning': 'Plants such as wheat or potatoes grown for food.',
         'sentence': 'The farmer watered his crops.',
         'synonyms': [], 'antonyms': []},
        {'word': 'orchard', 'pos': 'noun', 'meaning': 'A piece of land where fruit trees are grown.',
         'sentence': 'We picked apples in the orchard.',
         'synonyms': [], 'antonyms': []},
        {'word': 'scarecrow', 'pos': 'noun', 'meaning': 'A model of a person put in a field to frighten birds away.',
         'sentence': 'A scarecrow stood in the middle of the field.',
         'synonyms': [], 'antonyms': []},
        {'word': 'fence', 'pos': 'noun', 'meaning': 'A barrier around a field or garden.',
         'sentence': 'The sheep stayed inside the fence.',
         'synonyms': ['barrier'], 'antonyms': []},
        {'word': 'graze', 'pos': 'verb', 'meaning': 'To eat grass that is growing in a field.',
         'sentence': 'Cows graze on the hillside.',
         'synonyms': ['feed'], 'antonyms': []},
        {'word': 'shepherd', 'pos': 'noun', 'meaning': 'A person who looks after sheep.',
         'sentence': 'The shepherd led his flock down the hill.',
         'synonyms': [], 'antonyms': []},
    ]},
    {'week': 20, 'theme': 'Art and Colours', 'words': [
        {'word': 'paintbrush', 'pos': 'noun', 'meaning': 'A brush used for painting.',
         'sentence': 'She dipped her paintbrush in the blue paint.',
         'synonyms': [], 'antonyms': []},
        {'word': 'sketch', 'pos': 'noun', 'meaning': 'A quick drawing that is not finished in detail.',
         'sentence': 'He made a sketch of the old oak tree.',
         'synonyms': ['drawing'], 'antonyms': []},
        {'word': 'canvas', 'pos': 'noun', 'meaning': 'A strong cloth that artists paint on.',
         'sentence': 'The artist stretched a canvas onto a frame.',
         'synonyms': [], 'antonyms': []},
        {'word': 'palette', 'pos': 'noun', 'meaning': 'A board on which an artist mixes paints.',
         'sentence': 'She mixed yellow and blue on her palette.',
         'synonyms': [], 'antonyms': []},
        {'word': 'portrait', 'pos': 'noun', 'meaning': 'A picture of a person\'s face.',
         'sentence': 'We painted a portrait of our teacher.',
         'synonyms': [], 'antonyms': []},
        {'word': 'shade', 'pos': 'noun', 'meaning': 'A darker or lighter version of a colour.',
         'sentence': 'I painted the sky in a pale shade of blue.',
         'synonyms': ['tint'], 'antonyms': []},
        {'word': 'sculpture', 'pos': 'noun', 'meaning': 'A solid artwork made from clay, stone or metal.',
         'sentence': 'The sculpture in the park looks like a giant bird.',
         'synonyms': ['statue'], 'antonyms': []},
        {'word': 'pattern', 'pos': 'noun', 'meaning': 'A design made of shapes or lines that repeat.',
         'sentence': 'The rug had a pattern of red stripes.',
         'synonyms': ['design'], 'antonyms': []},
        {'word': 'bright', 'pos': 'adjective', 'meaning': 'Strong and easy to see.',
         'sentence': 'She wore a bright yellow raincoat.',
         'synonyms': ['vivid', 'vibrant'], 'antonyms': ['dull', 'dim']},
        {'word': 'mural', 'pos': 'noun', 'meaning': 'A large painting made directly on a wall.',
         'sentence': 'Our class helped paint the mural on the wall.',
         'synonyms': [], 'antonyms': []},
    ]},
    {'week': 21, 'theme': 'Time and Seasons', 'words': [
        {'word': 'calendar', 'pos': 'noun', 'meaning': 'A chart that shows the days, weeks and months of the year.',
         'sentence': 'I marked my birthday on the calendar.',
         'synonyms': [], 'antonyms': []},
        {'word': 'autumn', 'pos': 'noun', 'meaning': 'The season between summer and winter when leaves fall.',
         'sentence': 'The leaves turn orange in autumn.',
         'synonyms': [], 'antonyms': ['spring']},
        {'word': 'minute', 'pos': 'noun', 'meaning': 'A period of time equal to sixty seconds.',
         'sentence': 'Wait one minute while I find my shoes.',
         'synonyms': [], 'antonyms': []},
        {'word': 'century', 'pos': 'noun', 'meaning': 'A period of one hundred years.',
         'sentence': 'The castle was built nearly a century ago.',
         'synonyms': [], 'antonyms': []},
        {'word': 'season', 'pos': 'noun', 'meaning': 'One of the four parts of the year: spring, summer, autumn or winter.',
         'sentence': 'My favourite season is summer.',
         'synonyms': [], 'antonyms': []},
        {'word': 'midnight', 'pos': 'noun', 'meaning': 'Twelve o\'clock at night.',
         'sentence': 'The clock struck midnight.',
         'synonyms': [], 'antonyms': ['noon']},
        {'word': 'sunrise', 'pos': 'noun', 'meaning': 'The time in the morning when the sun first appears.',
         'sentence': 'We woke early to watch the sunrise.',
         'synonyms': ['dawn'], 'antonyms': ['sunset']},
        {'word': 'sunset', 'pos': 'noun', 'meaning': 'The time in the evening when the sun goes down.',
         'sentence': 'The sunset painted the sky orange.',
         'synonyms': ['dusk'], 'antonyms': ['sunrise']},
        {'word': 'weekend', 'pos': 'noun', 'meaning': 'Saturday and Sunday.',
         'sentence': 'We go to the park every weekend.',
         'synonyms': [], 'antonyms': []},
        {'word': 'hour', 'pos': 'noun', 'meaning': 'A period of time equal to sixty minutes.',
         'sentence': 'The film lasted for an hour and a half.',
         'synonyms': [], 'antonyms': []},
    ]},
    {'week': 22, 'theme': 'Jobs and People', 'words': [
        {'word': 'firefighter', 'pos': 'noun', 'meaning': 'A person whose job is to put out fires and help in emergencies.',
         'sentence': 'The firefighter climbed down the ladder.',
         'synonyms': [], 'antonyms': []},
        {'word': 'nurse', 'pos': 'noun', 'meaning': 'A person trained to look after sick or injured people.',
         'sentence': 'The nurse gave me a sticker.',
         'synonyms': [], 'antonyms': []},
        {'word': 'engineer', 'pos': 'noun', 'meaning': 'A person who designs and builds machines, roads or bridges.',
         'sentence': 'The engineer drew plans for the new bridge.',
         'synonyms': [], 'antonyms': []},
        {'word': 'pilot', 'pos': 'noun', 'meaning': 'A person who flies an aeroplane.',
         'sentence': 'The pilot welcomed us aboard.',
         'synonyms': [], 'antonyms': []},
        {'word': 'plumber', 'pos': 'noun', 'meaning': 'A person who fits and repairs water pipes.',
         'sentence': 'The plumber fixed the dripping tap.',
         'synonyms': [], 'antonyms': []},
        {'word': 'carpenter', 'pos': 'noun', 'meaning': 'A person who makes things from wood.',
         'sentence': 'The carpenter built a bookshelf.',
         'synonyms': [], 'antonyms': []},
        {'word': 'scientist', 'pos': 'noun', 'meaning': 'A person who studies the world through experiments.',
         'sentence': 'The scientist studied the tiny insects.',
         'synonyms': [], 'antonyms': []},
        {'word': 'journalist', 'pos': 'noun', 'meaning': 'A person who writes news stories for papers or websites.',
         'sentence': 'The journalist interviewed the school captain.',
         'synonyms': ['reporter'], 'antonyms': []},
        {'word': 'chef', 'pos': 'noun', 'meaning': 'A person who cooks meals as a job.',
         'sentence': 'The chef made pancakes for everyone.',
         'synonyms': ['cook'], 'antonyms': []},
        {'word': 'dentist', 'pos': 'noun', 'meaning': 'A person who looks after your teeth.',
         'sentence': 'The dentist checked my teeth.',
         'synonyms': [], 'antonyms': []},
    ]},
    {'week': 23, 'theme': 'Camping and Adventure', 'words': [
        {'word': 'tent', 'pos': 'noun', 'meaning': 'A shelter made of cloth that you put up outdoors.',
         'sentence': 'We put up the tent before it got dark.',
         'synonyms': [], 'antonyms': []},
        {'word': 'campfire', 'pos': 'noun', 'meaning': 'A fire made outdoors at a camp.',
         'sentence': 'We toasted marshmallows over the campfire.',
         'synonyms': [], 'antonyms': []},
        {'word': 'compass', 'pos': 'noun', 'meaning': 'A tool with a needle that points north.',
         'sentence': 'Use the compass to find the way.',
         'synonyms': [], 'antonyms': []},
        {'word': 'backpack', 'pos': 'noun', 'meaning': 'A bag that you carry on your back.',
         'sentence': 'I packed a sandwich in my backpack.',
         'synonyms': ['rucksack'], 'antonyms': []},
        {'word': 'trail', 'pos': 'noun', 'meaning': 'A path through the countryside.',
         'sentence': 'The trail wound up the hill.',
         'synonyms': ['path', 'track'], 'antonyms': []},
        {'word': 'adventure', 'pos': 'noun', 'meaning': 'An exciting or unusual experience.',
         'sentence': 'Our camping trip was a great adventure.',
         'synonyms': ['journey', 'quest'], 'antonyms': []},
        {'word': 'torch', 'pos': 'noun', 'meaning': 'A small electric light that you can carry.',
         'sentence': 'I shone my torch into the tent.',
         'synonyms': ['flashlight'], 'antonyms': []},
        {'word': 'explore', 'pos': 'verb', 'meaning': 'To travel around a place to find out about it.',
         'sentence': 'We love to explore the woods near the camp.',
         'synonyms': ['investigate', 'discover'], 'antonyms': []},
        {'word': 'hike', 'pos': 'noun', 'meaning': 'A long walk in the countryside.',
         'sentence': 'We went on a hike to the waterfall.',
         'synonyms': ['ramble', 'trek'], 'antonyms': []},
        {'word': 'map', 'pos': 'noun', 'meaning': 'A drawing that shows where places are.',
         'sentence': 'Dad checked the map to find the campsite.',
         'synonyms': [], 'antonyms': []},
    ]},
    {'week': 24, 'theme': 'Minibeasts', 'words': [
        {'word': 'caterpillar', 'pos': 'noun', 'meaning': 'A small, long creature that will turn into a butterfly or moth.',
         'sentence': 'A green caterpillar crawled along the leaf.',
         'synonyms': ['larva'], 'antonyms': []},
        {'word': 'butterfly', 'pos': 'noun', 'meaning': 'An insect with large, colourful wings.',
         'sentence': 'A butterfly landed on the flower.',
         'synonyms': [], 'antonyms': []},
        {'word': 'beetle', 'pos': 'noun', 'meaning': 'An insect with hard wing cases.',
         'sentence': 'A beetle crawled across the log.',
         'synonyms': [], 'antonyms': []},
        {'word': 'spider', 'pos': 'noun', 'meaning': 'A small creature with eight legs that spins webs.',
         'sentence': 'A spider spun a web between the twigs.',
         'synonyms': [], 'antonyms': []},
        {'word': 'ladybird', 'pos': 'noun', 'meaning': 'A small round beetle, usually red with black spots.',
         'sentence': 'A ladybird landed on my finger.',
         'synonyms': [], 'antonyms': []},
        {'word': 'antenna', 'pos': 'noun', 'meaning': 'One of the two thin feelers on an insect\'s head.',
         'sentence': 'The ant waved its antenna in the air.',
         'synonyms': ['feeler'], 'antonyms': []},
        {'word': 'insect', 'pos': 'noun', 'meaning': 'A small creature with six legs and a body in three parts.',
         'sentence': 'An ant is an insect.',
         'synonyms': ['bug'], 'antonyms': []},
        {'word': 'cocoon', 'pos': 'noun', 'meaning': 'A silky case that some insects make to protect themselves while they change.',
         'sentence': 'The caterpillar spun a cocoon around itself.',
         'synonyms': ['chrysalis'], 'antonyms': []},
        {'word': 'wriggle', 'pos': 'verb', 'meaning': 'To twist and turn with small movements.',
         'sentence': 'The worm began to wriggle in the soil.',
         'synonyms': ['squirm', 'writhe'], 'antonyms': []},
        {'word': 'swarm', 'pos': 'noun', 'meaning': 'A large group of insects moving together.',
         'sentence': 'A swarm of bees hovered above the hive.',
         'synonyms': ['cloud'], 'antonyms': []},
    ]},
    {'week': 25, 'theme': 'Shopping and Money', 'words': [
        {'word': 'price', 'pos': 'noun', 'meaning': 'The amount of money that you have to pay for something.',
         'sentence': 'The price of the book is five pounds.',
         'synonyms': ['cost'], 'antonyms': []},
        {'word': 'receipt', 'pos': 'noun', 'meaning': 'A piece of paper showing that you have paid for something.',
         'sentence': 'Keep the receipt in case it breaks.',
         'synonyms': [], 'antonyms': []},
        {'word': 'bargain', 'pos': 'noun', 'meaning': 'Something that costs less than usual.',
         'sentence': 'These shoes were a real bargain.',
         'synonyms': ['good deal'], 'antonyms': []},
        {'word': 'customer', 'pos': 'noun', 'meaning': 'A person who buys things from a shop.',
         'sentence': 'The customer asked for a bag.',
         'synonyms': ['shopper'], 'antonyms': []},
        {'word': 'cashier', 'pos': 'noun', 'meaning': 'A person who takes payment in a shop.',
         'sentence': 'The cashier gave me my change.',
         'synonyms': [], 'antonyms': []},
        {'word': 'coins', 'pos': 'noun', 'meaning': 'Small round pieces of metal used as money.',
         'sentence': 'I counted the coins in my piggy bank.',
         'synonyms': [], 'antonyms': ['notes']},
        {'word': 'budget', 'pos': 'noun', 'meaning': 'A plan for how much money you can spend.',
         'sentence': 'We made a budget for our school trip.',
         'synonyms': [], 'antonyms': []},
        {'word': 'save', 'pos': 'verb', 'meaning': 'To keep money to use later.',
         'sentence': 'I save part of my pocket money each week.',
         'synonyms': ['put aside'], 'antonyms': ['spend']},
        {'word': 'afford', 'pos': 'verb', 'meaning': 'To have enough money to buy something.',
         'sentence': 'We cannot afford a new bike this month.',
         'synonyms': [], 'antonyms': []},
        {'word': 'discount', 'pos': 'noun', 'meaning': 'An amount taken off the normal price.',
         'sentence': 'There is a discount on all books today.',
         'synonyms': ['reduction'], 'antonyms': []},
    ]},
    {'week': 26, 'theme': 'Myths and Legends', 'words': [
        {'word': 'dragon', 'pos': 'noun', 'meaning': 'An imaginary creature that often breathes fire.',
         'sentence': 'A dragon guarded the golden treasure in the story.',
         'synonyms': [], 'antonyms': []},
        {'word': 'wizard', 'pos': 'noun', 'meaning': 'A man in stories who can do magic.',
         'sentence': 'The wizard waved his wand and the rabbit appeared.',
         'synonyms': ['sorcerer'], 'antonyms': []},
        {'word': 'legend', 'pos': 'noun', 'meaning': 'An old story passed down that may be partly true.',
         'sentence': 'Many people know the legend of Robin Hood.',
         'synonyms': ['tale', 'myth'], 'antonyms': []},
        {'word': 'myth', 'pos': 'noun', 'meaning': 'An old story that explains something about nature or the gods.',
         'sentence': 'The Greek myth tells how the sun crossed the sky.',
         'synonyms': ['legend'], 'antonyms': ['fact']},
        {'word': 'hero', 'pos': 'noun', 'meaning': 'A person who is admired for being brave or good.',
         'sentence': 'The hero rescued the village in the legend.',
         'synonyms': ['champion'], 'antonyms': []},
        {'word': 'quest', 'pos': 'noun', 'meaning': 'A long search for something important.',
         'sentence': 'The knight went on a quest to find the golden cup.',
         'synonyms': ['search', 'mission'], 'antonyms': []},
        {'word': 'treasure', 'pos': 'noun', 'meaning': 'A collection of valuable things like gold and jewels.',
         'sentence': 'The pirates buried their treasure on the island.',
         'synonyms': ['riches'], 'antonyms': []},
        {'word': 'castle', 'pos': 'noun', 'meaning': 'A large, strong building with thick walls, built long ago.',
         'sentence': 'The castle stood on a high hill.',
         'synonyms': ['fortress'], 'antonyms': []},
        {'word': 'kingdom', 'pos': 'noun', 'meaning': 'A country ruled by a king or queen.',
         'sentence': 'The kingdom was ruled by a kind queen.',
         'synonyms': ['realm'], 'antonyms': []},
        {'word': 'enchanted', 'pos': 'adjective', 'meaning': 'Under a magic spell.',
         'sentence': 'The enchanted forest glowed with silver light.',
         'synonyms': ['magical'], 'antonyms': ['ordinary']},
    ]},
    {'week': 27, 'theme': 'Kindness and Helping', 'words': [
        {'word': 'generous', 'pos': 'adjective', 'meaning': 'Willing to give more than is expected.',
         'sentence': 'The generous man shared his lunch.',
         'synonyms': ['giving', 'kind'], 'antonyms': ['selfish', 'mean']},
        {'word': 'polite', 'pos': 'adjective', 'meaning': 'Having good manners.',
         'sentence': 'It is polite to say thank you.',
         'synonyms': ['courteous', 'respectful'], 'antonyms': ['rude']},
        {'word': 'thoughtful', 'pos': 'adjective', 'meaning': 'Thinking about the feelings of other people.',
         'sentence': 'It was thoughtful of her to bring me flowers.',
         'synonyms': ['caring', 'kind'], 'antonyms': ['thoughtless', 'selfish']},
        {'word': 'volunteer', 'pos': 'noun', 'meaning': 'A person who offers to do a job without being paid.',
         'sentence': 'A volunteer helped to serve the soup.',
         'synonyms': ['helper'], 'antonyms': []},
        {'word': 'comfort', 'pos': 'verb', 'meaning': 'To make someone feel better when they are sad.',
         'sentence': 'I tried to comfort my friend when she lost her toy.',
         'synonyms': ['console', 'soothe'], 'antonyms': ['upset']},
        {'word': 'support', 'pos': 'verb', 'meaning': 'To help someone and show that you are on their side.',
         'sentence': 'We all came to support the team.',
         'synonyms': ['help', 'back'], 'antonyms': ['abandon']},
        {'word': 'encourage', 'pos': 'verb', 'meaning': 'To give someone confidence to do something.',
         'sentence': 'My teacher will encourage me to try harder.',
         'synonyms': ['inspire', 'cheer'], 'antonyms': ['discourage']},
        {'word': 'charity', 'pos': 'noun', 'meaning': 'An organisation that raises money to help people in need.',
         'sentence': 'We ran a bake sale for charity.',
         'synonyms': [], 'antonyms': []},
        {'word': 'forgive', 'pos': 'verb', 'meaning': 'To stop being angry with someone who has done something wrong.',
         'sentence': 'I forgive you for breaking my pencil.',
         'synonyms': ['pardon'], 'antonyms': ['blame']},
        {'word': 'donate', 'pos': 'verb', 'meaning': 'To give something to help others.',
         'sentence': 'We donate our old books to the library.',
         'synonyms': ['give'], 'antonyms': []},
    ]},
    {'week': 28, 'theme': 'Science Lab', 'words': [
        {'word': 'experiment', 'pos': 'noun', 'meaning': 'A test carried out to find something out.',
         'sentence': 'We did an experiment with ice and salt.',
         'synonyms': ['test', 'trial'], 'antonyms': []},
        {'word': 'microscope', 'pos': 'noun', 'meaning': 'A tool that makes very tiny things look much bigger.',
         'sentence': 'We looked at a leaf under the microscope.',
         'synonyms': [], 'antonyms': []},
        {'word': 'observe', 'pos': 'verb', 'meaning': 'To watch something carefully.',
         'sentence': 'Observe what happens to the water when it freezes.',
         'synonyms': ['watch', 'notice'], 'antonyms': ['ignore']},
        {'word': 'magnet', 'pos': 'noun', 'meaning': 'An object that pulls iron and steel towards it.',
         'sentence': 'The magnet picked up all the pins.',
         'synonyms': [], 'antonyms': []},
        {'word': 'liquid', 'pos': 'noun', 'meaning': 'A substance that flows and can be poured, like water.',
         'sentence': 'Water is a liquid.',
         'synonyms': ['fluid'], 'antonyms': ['solid']},
        {'word': 'solid', 'pos': 'noun', 'meaning': 'A substance that keeps its shape, like a stone.',
         'sentence': 'Ice is a solid.',
         'synonyms': [], 'antonyms': ['liquid']},
        {'word': 'measure', 'pos': 'verb', 'meaning': 'To find out the size or amount of something.',
         'sentence': 'Measure the water in the jug.',
         'synonyms': ['calculate'], 'antonyms': []},
        {'word': 'beaker', 'pos': 'noun', 'meaning': 'A glass or plastic container with straight sides used in labs.',
         'sentence': 'Pour the water into the beaker.',
         'synonyms': [], 'antonyms': []},
        {'word': 'result', 'pos': 'noun', 'meaning': 'What you find out at the end of an experiment.',
         'sentence': 'The result of our test surprised us.',
         'synonyms': ['outcome'], 'antonyms': []},
        {'word': 'goggles', 'pos': 'noun', 'meaning': 'Glasses that protect your eyes.',
         'sentence': 'Always wear goggles in the lab.',
         'synonyms': [], 'antonyms': []},
    ]},
    {'week': 29, 'theme': 'Caring for the Environment', 'words': [
        {'word': 'recycle', 'pos': 'verb', 'meaning': 'To treat used things so they can be used again.',
         'sentence': 'We recycle paper and glass at home.',
         'synonyms': ['reuse'], 'antonyms': ['waste']},
        {'word': 'pollution', 'pos': 'noun', 'meaning': 'Dirty or harmful things in the air, water or soil.',
         'sentence': 'Pollution from cars makes the air dirty.',
         'synonyms': [], 'antonyms': []},
        {'word': 'litter', 'pos': 'noun', 'meaning': 'Rubbish left lying around in public places.',
         'sentence': 'Please put your litter in the bin.',
         'synonyms': ['rubbish'], 'antonyms': []},
        {'word': 'conserve', 'pos': 'verb', 'meaning': 'To protect something and use it carefully.',
         'sentence': 'We conserve water by turning off the tap.',
         'synonyms': ['save', 'protect'], 'antonyms': ['waste']},
        {'word': 'protect', 'pos': 'verb', 'meaning': 'To keep something safe from harm.',
         'sentence': 'Trees protect the soil from washing away.',
         'synonyms': ['guard', 'defend'], 'antonyms': ['harm']},
        {'word': 'compost', 'pos': 'noun', 'meaning': 'Rotted leaves and food scraps used to feed the soil.',
         'sentence': 'We put vegetable peelings on the compost.',
         'synonyms': [], 'antonyms': []},
        {'word': 'waste', 'pos': 'noun', 'meaning': 'Things that are thrown away because they are not needed.',
         'sentence': 'Too much food waste is bad for the planet.',
         'synonyms': ['rubbish'], 'antonyms': []},
        {'word': 'endangered', 'pos': 'adjective', 'meaning': 'At risk of dying out completely.',
         'sentence': 'The panda is an endangered animal.',
         'synonyms': ['threatened'], 'antonyms': ['safe']},
        {'word': 'renewable', 'pos': 'adjective', 'meaning': 'Able to be used again and again without running out.',
         'sentence': 'Wind is a renewable source of energy.',
         'synonyms': [], 'antonyms': []},
        {'word': 'plastic', 'pos': 'noun', 'meaning': 'A light, strong material made by people.',
         'sentence': 'Plastic bottles can be recycled.',
         'synonyms': [], 'antonyms': []},
    ]},
    {'week': 30, 'theme': 'Tricky Spellings Review', 'words': [
        {'word': 'necessary', 'pos': 'adjective', 'meaning': 'Needed; something you cannot do without.',
         'sentence': 'It is necessary to wear a helmet when cycling.',
         'synonyms': ['essential', 'needed'], 'antonyms': ['unnecessary']},
        {'word': 'definitely', 'pos': 'adverb', 'meaning': 'Without any doubt; certainly.',
         'sentence': 'I will definitely be there on time.',
         'synonyms': ['certainly', 'surely'], 'antonyms': ['maybe']},
        {'word': 'beautiful', 'pos': 'adjective', 'meaning': 'Very pleasing to look at.',
         'sentence': 'The garden looked beautiful in the sun.',
         'synonyms': ['lovely', 'pretty'], 'antonyms': ['ugly']},
        {'word': 'friend', 'pos': 'noun', 'meaning': 'A person you like and enjoy spending time with.',
         'sentence': 'My friend and I walk to school together.',
         'synonyms': ['pal', 'mate'], 'antonyms': ['enemy']},
        {'word': 'because', 'pos': 'conjunction', 'meaning': 'For the reason that.',
         'sentence': 'I stayed in because it was raining.',
         'synonyms': ['since', 'as'], 'antonyms': []},
        {'word': 'believe', 'pos': 'verb', 'meaning': 'To think that something is true.',
         'sentence': 'I believe you are telling the truth.',
         'synonyms': ['trust', 'accept'], 'antonyms': ['doubt']},
        {'word': 'different', 'pos': 'adjective', 'meaning': 'Not the same as another.',
         'sentence': 'Each flower is a different colour.',
         'synonyms': ['unlike', 'distinct'], 'antonyms': ['same', 'alike']},
        {'word': 'disappear', 'pos': 'verb', 'meaning': 'To go out of sight.',
         'sentence': 'The rabbit seemed to disappear down the hole.',
         'synonyms': ['vanish'], 'antonyms': ['appear']},
        {'word': 'island', 'pos': 'noun', 'meaning': 'A piece of land with water all around it.',
         'sentence': 'We sailed to a small island.',
         'synonyms': ['isle'], 'antonyms': []},
        {'word': 'knowledge', 'pos': 'noun', 'meaning': 'What you know or have learned.',
         'sentence': 'Reading books adds to your knowledge.',
         'synonyms': ['understanding'], 'antonyms': ['ignorance']},
    ]},
]
