# Primary level word data: one entry per week.

PRIMARY_WORDS = [
    {'week': 1, 'theme': 'Feelings', 'words': [
        {'word': 'cheerful', 'pos': 'adjective', 'meaning': 'Noticeably happy and optimistic.',
         'sentence': 'The cheerful girl waved at everyone she passed.',
         'synonyms': ['happy', 'jolly'], 'antonyms': ['gloomy', 'sad']},
        {'word': 'anxious', 'pos': 'adjective', 'meaning': 'Feeling worried or nervous about something.',
         'sentence': 'He felt anxious before his first swimming lesson.',
         'synonyms': ['worried', 'nervous'], 'antonyms': ['calm', 'relaxed']},
        {'word': 'furious', 'pos': 'adjective', 'meaning': 'Extremely angry.',
         'sentence': 'Mum was furious when the dog chewed her shoes.',
         'synonyms': ['angry', 'livid'], 'antonyms': ['pleased', 'calm']},
        {'word': 'grateful', 'pos': 'adjective', 'meaning': 'Feeling or showing thanks.',
         'sentence': 'We were grateful for the warm soup on a cold day.',
         'synonyms': ['thankful'], 'antonyms': ['ungrateful']},
        {'word': 'lonely', 'pos': 'adjective', 'meaning': 'Sad because one has no friends or company.',
         'sentence': 'The new boy felt lonely on his first day.',
         'synonyms': ['alone', 'isolated'], 'antonyms': ['sociable']},
    ]},
    {'week': 2, 'theme': 'Nature', 'words': [
        {'word': 'meadow', 'pos': 'noun', 'meaning': 'A field of grass and wild flowers.',
         'sentence': 'Cows grazed quietly in the meadow.',
         'synonyms': ['field', 'pasture'], 'antonyms': []},
        {'word': 'blossom', 'pos': 'noun', 'meaning': 'A flower on a tree or bush.',
         'sentence': 'Pink blossom covered the cherry tree in spring.',
         'synonyms': ['bloom', 'flower'], 'antonyms': []},
        {'word': 'stream', 'pos': 'noun', 'meaning': 'A small, narrow river.',
         'sentence': 'We dipped our toes in the cool stream.',
         'synonyms': ['brook', 'creek'], 'antonyms': []},
        {'word': 'gentle', 'pos': 'adjective', 'meaning': 'Mild, soft or kind.',
         'sentence': 'A gentle breeze rustled the leaves.',
         'synonyms': ['soft', 'mild'], 'antonyms': ['harsh', 'rough']},
        {'word': 'thunder', 'pos': 'noun', 'meaning': 'The loud rumbling noise heard after lightning.',
         'sentence': 'The thunder was so loud that the windows shook.',
         'synonyms': ['rumble'], 'antonyms': []},
    ]},
    {'week': 3, 'theme': 'At School', 'words': [
        {'word': 'library', 'pos': 'noun', 'meaning': 'A room or building where books are kept for reading or borrowing.',
         'sentence': 'She borrowed three books from the library.',
         'synonyms': [], 'antonyms': []},
        {'word': 'explain', 'pos': 'verb', 'meaning': 'To make something clear by describing it.',
         'sentence': 'Can you explain how you solved the puzzle?',
         'synonyms': ['describe', 'clarify'], 'antonyms': ['confuse']},
        {'word': 'practise', 'pos': 'verb', 'meaning': 'To do something again and again to get better at it.',
         'sentence': 'I practise the piano every evening.',
         'synonyms': ['rehearse', 'train'], 'antonyms': []},
        {'word': 'answer', 'pos': 'noun', 'meaning': 'A reply to a question.',
         'sentence': 'He wrote his answer neatly in the box.',
         'synonyms': ['reply', 'response'], 'antonyms': ['question']},
        {'word': 'separate', 'pos': 'adjective', 'meaning': 'Forming a unit by itself; not joined.',
         'sentence': 'Keep the red and blue pencils in separate boxes.',
         'synonyms': ['apart', 'distinct'], 'antonyms': ['joined', 'together']},
    ]},
]
