# Secondary level word data: one entry per week.

SECONDARY_WORDS = [
    {'week': 1, 'theme': 'Character', 'words': [
        {'word': 'resilient', 'pos': 'adjective', 'meaning': 'Able to recover quickly from difficulties.',
         'sentence': 'The resilient team bounced back after losing the first match.',
         'synonyms': ['tough', 'hardy'], 'antonyms': ['fragile', 'vulnerable']},
        {'word': 'meticulous', 'pos': 'adjective', 'meaning': 'Showing great attention to detail.',
         'sentence': 'Her meticulous notes made revision easy.',
         'synonyms': ['careful', 'thorough'], 'antonyms': ['careless', 'sloppy']},
        {'word': 'humble', 'pos': 'adjective', 'meaning': 'Having a modest view of one\'s own importance.',
         'sentence': 'Despite winning, he remained humble.',
         'synonyms': ['modest'], 'antonyms': ['arrogant', 'proud']},
        {'word': 'diligent', 'pos': 'adjective', 'meaning': 'Having or showing care and effort in one\'s work.',
         'sentence': 'A diligent student checks every answer twice.',
         'synonyms': ['hardworking', 'industrious'], 'antonyms': ['lazy']},
        {'word': 'candid', 'pos': 'adjective', 'meaning': 'Truthful and straightforward.',
         'sentence': 'She gave a candid account of what happened.',
         'synonyms': ['frank', 'honest'], 'antonyms': ['evasive']},
        {'word': 'ambitious', 'pos': 'adjective', 'meaning': 'Having a strong desire to succeed or achieve something.',
         'sentence': 'The ambitious young chef dreamed of opening her own restaurant.',
         'synonyms': ['determined', 'driven'], 'antonyms': ['lazy', 'unambitious']},
        {'word': 'stubborn', 'pos': 'adjective', 'meaning': 'Refusing to change your mind or way of doing things.',
         'sentence': 'The stubborn donkey would not move an inch.',
         'synonyms': ['obstinate', 'headstrong'], 'antonyms': ['flexible', 'willing']},
        {'word': 'compassionate', 'pos': 'adjective', 'meaning': 'Feeling sympathy and wanting to help others.',
         'sentence': 'A compassionate neighbour brought soup when I was ill.',
         'synonyms': ['caring', 'kind-hearted'], 'antonyms': ['heartless', 'cruel']},
        {'word': 'integrity', 'pos': 'noun', 'meaning': 'Being honest and having strong moral principles.',
         'sentence': 'The judge was respected for her integrity.',
         'synonyms': ['honesty', 'honour'], 'antonyms': ['dishonesty']},
        {'word': 'tenacious', 'pos': 'adjective', 'meaning': 'Holding on firmly and not giving up.',
         'sentence': 'The tenacious climber kept going despite the rain.',
         'synonyms': ['persistent', 'determined'], 'antonyms': ['weak', 'hesitant']},
    ]},
    {'week': 2, 'theme': 'Debate', 'words': [
        {'word': 'persuade', 'pos': 'verb', 'meaning': 'To convince someone to do or believe something.',
         'sentence': 'He tried to persuade the class to vote for him.',
         'synonyms': ['convince', 'coax'], 'antonyms': ['dissuade']},
        {'word': 'contradict', 'pos': 'verb', 'meaning': 'To state the opposite of what someone has said.',
         'sentence': 'The evidence seemed to contradict his story.',
         'synonyms': ['dispute', 'oppose'], 'antonyms': ['confirm', 'agree']},
        {'word': 'rhetoric', 'pos': 'noun', 'meaning': 'The art of effective or persuasive speaking or writing.',
         'sentence': 'The speech was full of powerful rhetoric.',
         'synonyms': ['oratory', 'eloquence'], 'antonyms': []},
        {'word': 'concede', 'pos': 'verb', 'meaning': 'To admit that something is true after first denying it.',
         'sentence': 'She had to concede that her opponent made a good point.',
         'synonyms': ['admit', 'acknowledge'], 'antonyms': ['deny']},
        {'word': 'biased', 'pos': 'adjective', 'meaning': 'Unfairly favouring one side over another.',
         'sentence': 'The referee was accused of being biased.',
         'synonyms': ['partial', 'one-sided'], 'antonyms': ['impartial', 'fair']},
        {'word': 'argument', 'pos': 'noun', 'meaning': 'A set of reasons given to support or oppose an idea.',
         'sentence': 'Her argument for a longer lunch break was convincing.',
         'synonyms': ['case', 'reasoning'], 'antonyms': []},
        {'word': 'rebuttal', 'pos': 'noun', 'meaning': 'A reply that shows that a claim is wrong.',
         'sentence': 'He prepared a rebuttal to every point his opponents made.',
         'synonyms': ['response', 'reply'], 'antonyms': []},
        {'word': 'claim', 'pos': 'noun', 'meaning': 'A statement that something is true, often without proof.',
         'sentence': 'Her claim that homework is useless needs evidence.',
         'synonyms': ['assertion'], 'antonyms': ['denial']},
        {'word': 'opinion', 'pos': 'noun', 'meaning': 'A personal view or belief that is not necessarily a fact.',
         'sentence': 'In my opinion, school uniforms are a good idea.',
         'synonyms': ['view', 'belief'], 'antonyms': ['fact']},
        {'word': 'stance', 'pos': 'noun', 'meaning': 'The position that someone takes on an issue.',
         'sentence': 'The mayor took a firm stance on recycling.',
         'synonyms': ['position', 'attitude'], 'antonyms': []},
    ]},
    {'week': 3, 'theme': 'Exploration and Discovery', 'words': [
        {'word': 'expedition', 'pos': 'noun', 'meaning': 'A long journey made for a special purpose such as exploring.',
         'sentence': 'The expedition set off to map the remote island.',
         'synonyms': ['journey', 'mission'], 'antonyms': []},
        {'word': 'uncharted', 'pos': 'adjective', 'meaning': 'Not yet explored or mapped.',
         'sentence': 'The ship sailed into uncharted waters.',
         'synonyms': ['unexplored', 'unknown'], 'antonyms': ['mapped', 'familiar']},
        {'word': 'pioneer', 'pos': 'noun', 'meaning': 'A person who is among the first to explore or develop something new.',
         'sentence': 'She was a pioneer of deep-sea research.',
         'synonyms': ['trailblazer', 'explorer'], 'antonyms': ['follower']},
        {'word': 'navigate', 'pos': 'verb', 'meaning': 'To find the way to a place, using maps or instruments.',
         'sentence': 'Sailors once used the stars to navigate across the sea.',
         'synonyms': ['steer', 'guide'], 'antonyms': []},
        {'word': 'voyage', 'pos': 'noun', 'meaning': 'A long journey, especially by sea or through space.',
         'sentence': 'Columbus\'s voyage lasted more than two months.',
         'synonyms': ['journey', 'expedition'], 'antonyms': []},
        {'word': 'terrain', 'pos': 'noun', 'meaning': 'A stretch of land and its physical features.',
         'sentence': 'The rocky terrain was hard to cross.',
         'synonyms': ['landscape', 'ground'], 'antonyms': []},
        {'word': 'frontier', 'pos': 'noun', 'meaning': 'The edge of the known or settled part of a land.',
         'sentence': 'Settlers travelled to the western frontier.',
         'synonyms': ['border', 'boundary'], 'antonyms': []},
        {'word': 'venture', 'pos': 'noun', 'meaning': 'A new activity or journey that involves some risk.',
         'sentence': 'The trip to the rainforest was an exciting venture.',
         'synonyms': ['undertaking', 'adventure'], 'antonyms': []},
        {'word': 'curiosity', 'pos': 'noun', 'meaning': 'A strong desire to know or learn something.',
         'sentence': 'Curiosity led her to open the dusty old atlas.',
         'synonyms': ['inquisitiveness'], 'antonyms': ['apathy', 'indifference']},
        {'word': 'explorer', 'pos': 'noun', 'meaning': 'A person who travels to unfamiliar places to learn about them.',
         'sentence': 'The explorer kept a diary of the journey.',
         'synonyms': ['adventurer', 'traveller'], 'antonyms': []},
    ]},
    {'week': 4, 'theme': 'Technology and Gaming', 'words': [
        {'word': 'algorithm', 'pos': 'noun', 'meaning': 'A set of step-by-step instructions that a computer follows.',
         'sentence': 'The algorithm sorts the scores from highest to lowest.',
         'synonyms': ['procedure', 'formula'], 'antonyms': []},
        {'word': 'avatar', 'pos': 'noun', 'meaning': 'A character that represents a player in a game.',
         'sentence': 'I designed an avatar with a blue cap.',
         'synonyms': ['icon', 'character'], 'antonyms': []},
        {'word': 'bandwidth', 'pos': 'noun', 'meaning': 'The amount of data that can be sent over an internet connection at once.',
         'sentence': 'Streaming video uses a lot of bandwidth.',
         'synonyms': ['capacity'], 'antonyms': []},
        {'word': 'console', 'pos': 'noun', 'meaning': 'A device used to play video games on a screen.',
         'sentence': 'He plugged the console into the television.',
         'synonyms': [], 'antonyms': []},
        {'word': 'download', 'pos': 'verb', 'meaning': 'To copy a file from the internet to your own device.',
         'sentence': 'You can download the game for free.',
         'synonyms': ['transfer'], 'antonyms': ['upload']},
        {'word': 'encryption', 'pos': 'noun', 'meaning': 'Turning information into a secret code to keep it safe.',
         'sentence': 'Encryption keeps your passwords private online.',
         'synonyms': ['coding'], 'antonyms': []},
        {'word': 'multiplayer', 'pos': 'adjective', 'meaning': 'Allowing more than one person to play a game together.',
         'sentence': 'We played a multiplayer game with friends online.',
         'synonyms': [], 'antonyms': ['solo']},
        {'word': 'pixel', 'pos': 'noun', 'meaning': 'One of the tiny dots that make up a picture on a screen.',
         'sentence': 'Each pixel on the screen glowed a different colour.',
         'synonyms': ['dot'], 'antonyms': []},
        {'word': 'programmer', 'pos': 'noun', 'meaning': 'A person who writes instructions for computers.',
         'sentence': 'The programmer fixed a bug in the game.',
         'synonyms': ['coder', 'developer'], 'antonyms': []},
        {'word': 'virtual', 'pos': 'adjective', 'meaning': 'Existing on a computer rather than in the real world.',
         'sentence': 'We toured the museum in a virtual tour.',
         'synonyms': ['digital', 'simulated'], 'antonyms': ['real', 'physical']},
    ]},
    {'week': 5, 'theme': 'Ancient Civilisations', 'words': [
        {'word': 'pharaoh', 'pos': 'noun', 'meaning': 'A ruler of ancient Egypt.',
         'sentence': 'The pharaoh was buried in a great pyramid.',
         'synonyms': ['king', 'ruler'], 'antonyms': []},
        {'word': 'pyramid', 'pos': 'noun', 'meaning': 'A huge stone building with a square base and triangular sides.',
         'sentence': 'Workers took years to build the pyramid.',
         'synonyms': [], 'antonyms': []},
        {'word': 'archaeologist', 'pos': 'noun', 'meaning': 'A person who studies the past by digging up old objects.',
         'sentence': 'The archaeologist carefully brushed the soil off the pottery.',
         'synonyms': [], 'antonyms': []},
        {'word': 'empire', 'pos': 'noun', 'meaning': 'A group of countries or lands ruled by one government or ruler.',
         'sentence': 'The Roman empire stretched across Europe.',
         'synonyms': ['kingdom', 'realm'], 'antonyms': []},
        {'word': 'hieroglyph', 'pos': 'noun', 'meaning': 'A picture or symbol used in ancient Egyptian writing.',
         'sentence': 'Each hieroglyph stood for a word or sound.',
         'synonyms': ['symbol'], 'antonyms': []},
        {'word': 'dynasty', 'pos': 'noun', 'meaning': 'A series of rulers from the same family.',
         'sentence': 'The Ming dynasty ruled China for nearly three hundred years.',
         'synonyms': ['family', 'line'], 'antonyms': []},
        {'word': 'ruins', 'pos': 'noun', 'meaning': 'The remains of old buildings that have fallen down.',
         'sentence': 'We explored the ruins of an ancient temple.',
         'synonyms': ['remains', 'wreckage'], 'antonyms': []},
        {'word': 'scribe', 'pos': 'noun', 'meaning': 'A person who copied or wrote documents before printing existed.',
         'sentence': 'The scribe wrote the king\'s laws on papyrus.',
         'synonyms': ['writer'], 'antonyms': []},
        {'word': 'temple', 'pos': 'noun', 'meaning': 'A building used for worship.',
         'sentence': 'People brought offerings to the temple.',
         'synonyms': ['shrine'], 'antonyms': []},
        {'word': 'mosaic', 'pos': 'noun', 'meaning': 'A picture made of many small pieces of coloured stone or glass.',
         'sentence': 'The Romans made a mosaic for the floor.',
         'synonyms': [], 'antonyms': []},
    ]},
    {'week': 6, 'theme': 'Our Planet', 'words': [
        {'word': 'ecosystem', 'pos': 'noun', 'meaning': 'A community of living things and their environment working together.',
         'sentence': 'A pond is a small ecosystem.',
         'synonyms': ['habitat', 'environment'], 'antonyms': []},
        {'word': 'biodiversity', 'pos': 'noun', 'meaning': 'The variety of plant and animal life in a place.',
         'sentence': 'The rainforest has remarkable biodiversity.',
         'synonyms': ['variety'], 'antonyms': []},
        {'word': 'atmosphere', 'pos': 'noun', 'meaning': 'The layer of gases around the Earth.',
         'sentence': 'The atmosphere protects us from harmful rays.',
         'synonyms': ['air', 'sky'], 'antonyms': []},
        {'word': 'continent', 'pos': 'noun', 'meaning': 'One of the seven large land masses on Earth.',
         'sentence': 'Africa is the second largest continent.',
         'synonyms': ['landmass'], 'antonyms': []},
        {'word': 'equator', 'pos': 'noun', 'meaning': 'The imaginary line around the middle of the Earth.',
         'sentence': 'It is very hot near the equator.',
         'synonyms': [], 'antonyms': []},
        {'word': 'hemisphere', 'pos': 'noun', 'meaning': 'One half of the Earth.',
         'sentence': 'Australia is in the southern hemisphere.',
         'synonyms': [], 'antonyms': []},
        {'word': 'glacier', 'pos': 'noun', 'meaning': 'A huge, slow-moving river of ice.',
         'sentence': 'The glacier carved a deep valley over thousands of years.',
         'synonyms': ['ice sheet'], 'antonyms': []},
        {'word': 'erosion', 'pos': 'noun', 'meaning': 'The slow wearing away of rock or soil by wind or water.',
         'sentence': 'Erosion has shaped the cliffs along the coast.',
         'synonyms': ['weathering'], 'antonyms': []},
        {'word': 'climate', 'pos': 'noun', 'meaning': 'The usual weather of a place over many years.',
         'sentence': 'The climate in the desert is hot and dry.',
         'synonyms': ['weather pattern'], 'antonyms': []},
        {'word': 'tectonic', 'pos': 'adjective', 'meaning': 'Relating to the movement of the huge plates that form Earth\'s surface.',
         'sentence': 'Tectonic plates move a few centimetres each year.',
         'synonyms': [], 'antonyms': []},
    ]},
    {'week': 7, 'theme': 'Mysteries and Detectives', 'words': [
        {'word': 'clue', 'pos': 'noun', 'meaning': 'A piece of information that helps solve a puzzle or mystery.',
         'sentence': 'The torn map was the first clue.',
         'synonyms': ['hint', 'lead'], 'antonyms': []},
        {'word': 'detective', 'pos': 'noun', 'meaning': 'A person who investigates puzzles and finds answers.',
         'sentence': 'The detective examined the footprints with a magnifying glass.',
         'synonyms': ['investigator'], 'antonyms': []},
        {'word': 'suspicious', 'pos': 'adjective', 'meaning': 'Feeling that something is not quite right.',
         'sentence': 'She felt suspicious when the lights flickered.',
         'synonyms': ['doubtful', 'wary'], 'antonyms': ['trusting']},
        {'word': 'deduce', 'pos': 'verb', 'meaning': 'To work something out by careful thinking.',
         'sentence': 'From the muddy boots, I can deduce that he walked here.',
         'synonyms': ['conclude', 'infer'], 'antonyms': []},
        {'word': 'evidence', 'pos': 'noun', 'meaning': 'Facts or signs that help prove something.',
         'sentence': 'The scientist gathered evidence to support her idea.',
         'synonyms': ['proof', 'sign'], 'antonyms': []},
        {'word': 'riddle', 'pos': 'noun', 'meaning': 'A tricky question that has a clever answer.',
         'sentence': 'Can you solve this riddle?',
         'synonyms': ['puzzle', 'conundrum'], 'antonyms': []},
        {'word': 'cipher', 'pos': 'noun', 'meaning': 'A secret code used to hide the meaning of a message.',
         'sentence': 'They used a cipher to send secret notes.',
         'synonyms': ['code'], 'antonyms': []},
        {'word': 'witness', 'pos': 'noun', 'meaning': 'A person who sees something happen.',
         'sentence': 'The witness described what she saw.',
         'synonyms': ['observer'], 'antonyms': []},
        {'word': 'investigate', 'pos': 'verb', 'meaning': 'To look into something carefully to find the truth.',
         'sentence': 'The class decided to investigate the strange noise.',
         'synonyms': ['examine', 'explore'], 'antonyms': []},
        {'word': 'disguise', 'pos': 'noun', 'meaning': 'Clothes or make-up worn to hide who you are.',
         'sentence': 'The actor wore a disguise to avoid being recognised.',
         'synonyms': ['costume'], 'antonyms': []},
    ]},
    {'week': 8, 'theme': 'Teamwork and Leadership', 'words': [
        {'word': 'collaborate', 'pos': 'verb', 'meaning': 'To work together with others to achieve something.',
         'sentence': 'We will collaborate on the class science project.',
         'synonyms': ['cooperate'], 'antonyms': ['compete']},
        {'word': 'delegate', 'pos': 'verb', 'meaning': 'To give a part of your work or power to someone else.',
         'sentence': 'A good leader knows when to delegate.',
         'synonyms': ['assign'], 'antonyms': []},
        {'word': 'cooperate', 'pos': 'verb', 'meaning': 'To work together for a shared goal.',
         'sentence': 'The players must cooperate to win.',
         'synonyms': ['collaborate'], 'antonyms': []},
        {'word': 'inspire', 'pos': 'verb', 'meaning': 'To fill someone with the wish to do something good.',
         'sentence': 'Her speech will inspire the whole team.',
         'synonyms': ['motivate', 'encourage'], 'antonyms': ['discourage']},
        {'word': 'motivate', 'pos': 'verb', 'meaning': 'To give someone a reason to try hard.',
         'sentence': 'The coach tried to motivate the players.',
         'synonyms': ['encourage', 'drive'], 'antonyms': ['discourage']},
        {'word': 'mentor', 'pos': 'noun', 'meaning': 'An experienced person who gives advice to someone younger or newer.',
         'sentence': 'My mentor helped me prepare for the concert.',
         'synonyms': ['guide', 'adviser'], 'antonyms': []},
        {'word': 'leader', 'pos': 'noun', 'meaning': 'A person who guides or directs a group.',
         'sentence': 'The leader made sure everyone had a turn.',
         'synonyms': ['captain', 'chief'], 'antonyms': ['follower']},
        {'word': 'unity', 'pos': 'noun', 'meaning': 'The state of being joined together as one.',
         'sentence': 'The team showed great unity on the field.',
         'synonyms': ['togetherness', 'harmony'], 'antonyms': ['division']},
        {'word': 'strategy', 'pos': 'noun', 'meaning': 'A plan to achieve a goal.',
         'sentence': 'Our strategy was to pass the ball quickly.',
         'synonyms': ['plan', 'tactic'], 'antonyms': []},
        {'word': 'responsibility', 'pos': 'noun', 'meaning': 'A duty that you must carry out.',
         'sentence': 'Feeding the class pet is her responsibility.',
         'synonyms': ['duty', 'task'], 'antonyms': []},
    ]},
    {'week': 9, 'theme': 'The Human Body', 'words': [
        {'word': 'artery', 'pos': 'noun', 'meaning': 'A tube that carries blood from the heart to the rest of the body.',
         'sentence': 'Blood flows from the heart through an artery.',
         'synonyms': [], 'antonyms': []},
        {'word': 'cartilage', 'pos': 'noun', 'meaning': 'A strong, flexible material found in joints and the nose.',
         'sentence': 'Cartilage cushions the bones in your knee.',
         'synonyms': [], 'antonyms': []},
        {'word': 'digestion', 'pos': 'noun', 'meaning': 'The process of breaking down food so the body can use it.',
         'sentence': 'Digestion begins in the mouth.',
         'synonyms': [], 'antonyms': []},
        {'word': 'organ', 'pos': 'noun', 'meaning': 'A part of the body with a special job, such as the heart or lungs.',
         'sentence': 'The heart is an organ that pumps blood.',
         'synonyms': [], 'antonyms': []},
        {'word': 'oxygen', 'pos': 'noun', 'meaning': 'A gas in the air that living things need to breathe.',
         'sentence': 'Our lungs take oxygen from the air.',
         'synonyms': [], 'antonyms': []},
        {'word': 'pulse', 'pos': 'noun', 'meaning': 'The regular beat of blood that you can feel in your wrist.',
         'sentence': 'I took her pulse after the race.',
         'synonyms': ['heartbeat'], 'antonyms': []},
        {'word': 'respiratory', 'pos': 'adjective', 'meaning': 'Connected with breathing.',
         'sentence': 'The lungs are part of the respiratory system.',
         'synonyms': [], 'antonyms': []},
        {'word': 'tissue', 'pos': 'noun', 'meaning': 'A group of similar cells that work together in the body.',
         'sentence': 'Muscle tissue helps you to move.',
         'synonyms': [], 'antonyms': []},
        {'word': 'vertebrae', 'pos': 'noun', 'meaning': 'The small bones that make up your backbone.',
         'sentence': 'The vertebrae protect your spinal cord.',
         'synonyms': ['backbone'], 'antonyms': []},
        {'word': 'immune', 'pos': 'adjective', 'meaning': 'Protected against a disease.',
         'sentence': 'Vaccines help make us immune to illness.',
         'synonyms': ['protected'], 'antonyms': ['vulnerable']},
    ]},
    {'week': 10, 'theme': 'News and Media', 'words': [
        {'word': 'journalist', 'pos': 'noun', 'meaning': 'A person who gathers and reports news.',
         'sentence': 'The journalist wrote an article about the school fair.',
         'synonyms': ['reporter'], 'antonyms': []},
        {'word': 'headline', 'pos': 'noun', 'meaning': 'The title at the top of a newspaper story.',
         'sentence': 'The headline said that the town had a new park.',
         'synonyms': ['title', 'heading'], 'antonyms': []},
        {'word': 'editorial', 'pos': 'noun', 'meaning': 'A newspaper article that gives the opinion of the editor.',
         'sentence': 'The editorial praised the new library.',
         'synonyms': [], 'antonyms': []},
        {'word': 'broadcast', 'pos': 'verb', 'meaning': 'To send out a programme on television or radio.',
         'sentence': 'The channel will broadcast the match live.',
         'synonyms': ['transmit'], 'antonyms': []},
        {'word': 'reporter', 'pos': 'noun', 'meaning': 'A person who tells the news to the public.',
         'sentence': 'The reporter interviewed the winner.',
         'synonyms': ['journalist'], 'antonyms': []},
        {'word': 'publish', 'pos': 'verb', 'meaning': 'To print or release a book, article or story for the public.',
         'sentence': 'The magazine will publish her story next month.',
         'synonyms': ['print', 'issue'], 'antonyms': []},
        {'word': 'source', 'pos': 'noun', 'meaning': 'A person or place where information comes from.',
         'sentence': 'Always check that your source is reliable.',
         'synonyms': ['origin', 'reference'], 'antonyms': []},
        {'word': 'bulletin', 'pos': 'noun', 'meaning': 'A short news report on radio or television.',
         'sentence': 'We heard the weather on the evening bulletin.',
         'synonyms': ['report'], 'antonyms': []},
        {'word': 'correspondent', 'pos': 'noun', 'meaning': 'A journalist who reports from a particular place or on a particular topic.',
         'sentence': 'The foreign correspondent reported from Paris.',
         'synonyms': ['reporter'], 'antonyms': []},
        {'word': 'misinformation', 'pos': 'noun', 'meaning': 'Wrong or untrue information that is spread by mistake.',
         'sentence': 'Misinformation online can spread very quickly.',
         'synonyms': ['falsehood'], 'antonyms': ['truth']},
    ]},
    {'week': 11, 'theme': 'Inventors and Ideas', 'words': [
        {'word': 'innovation', 'pos': 'noun', 'meaning': 'A new idea, method or invention.',
         'sentence': 'The smartphone was a huge innovation.',
         'synonyms': ['invention', 'breakthrough'], 'antonyms': []},
        {'word': 'prototype', 'pos': 'noun', 'meaning': 'The first model of something, used for testing.',
         'sentence': 'The engineers tested the prototype in the car park.',
         'synonyms': ['model', 'sample'], 'antonyms': []},
        {'word': 'patent', 'pos': 'noun', 'meaning': 'A legal right that stops others from copying your invention.',
         'sentence': 'She applied for a patent for her gadget.',
         'synonyms': ['licence'], 'antonyms': []},
        {'word': 'visionary', 'pos': 'noun', 'meaning': 'A person with great imagination and ideas about the future.',
         'sentence': 'The visionary designed a city powered by the sun.',
         'synonyms': ['dreamer'], 'antonyms': []},
        {'word': 'blueprint', 'pos': 'noun', 'meaning': 'A detailed plan showing how something will be built.',
         'sentence': 'The architect studied the blueprint.',
         'synonyms': ['plan', 'design'], 'antonyms': []},
        {'word': 'ingenious', 'pos': 'adjective', 'meaning': 'Clever and inventive.',
         'sentence': 'It was an ingenious way to open the jar.',
         'synonyms': ['clever', 'inventive'], 'antonyms': ['foolish', 'dull']},
        {'word': 'engineer', 'pos': 'noun', 'meaning': 'A person who designs and builds machines or structures.',
         'sentence': 'The engineer solved the problem with a simple lever.',
         'synonyms': ['designer'], 'antonyms': []},
        {'word': 'concept', 'pos': 'noun', 'meaning': 'An idea or general plan.',
         'sentence': 'The concept for the game came from a dream.',
         'synonyms': ['idea'], 'antonyms': []},
        {'word': 'mechanism', 'pos': 'noun', 'meaning': 'The moving parts inside a machine.',
         'sentence': 'The clock has a delicate mechanism.',
         'synonyms': ['machinery'], 'antonyms': []},
        {'word': 'breakthrough', 'pos': 'noun', 'meaning': 'An important discovery or achievement.',
         'sentence': 'The scientists made a breakthrough in clean energy.',
         'synonyms': ['advance', 'discovery'], 'antonyms': ['setback']},
    ]},
    {'week': 12, 'theme': 'Extreme Weather', 'words': [
        {'word': 'hurricane', 'pos': 'noun', 'meaning': 'A very strong storm with powerful winds that forms over the sea.',
         'sentence': 'The hurricane brought strong winds and heavy rain.',
         'synonyms': ['cyclone', 'storm'], 'antonyms': []},
        {'word': 'drought', 'pos': 'noun', 'meaning': 'A long period with very little rain.',
         'sentence': 'The drought left the river almost dry.',
         'synonyms': ['dry spell'], 'antonyms': ['flood']},
        {'word': 'blizzard', 'pos': 'noun', 'meaning': 'A heavy snowstorm with strong winds.',
         'sentence': 'The blizzard closed the roads for two days.',
         'synonyms': ['snowstorm'], 'antonyms': []},
        {'word': 'monsoon', 'pos': 'noun', 'meaning': 'A season of very heavy rain in parts of Asia.',
         'sentence': 'The monsoon fills the rivers with water.',
         'synonyms': [], 'antonyms': []},
        {'word': 'tornado', 'pos': 'noun', 'meaning': 'A spinning column of air that reaches from a storm cloud to the ground.',
         'sentence': 'The tornado travelled across the open plain.',
         'synonyms': ['twister'], 'antonyms': []},
        {'word': 'torrential', 'pos': 'adjective', 'meaning': 'Falling very fast and heavily.',
         'sentence': 'Torrential rain made the streets look like rivers.',
         'synonyms': ['heavy'], 'antonyms': ['light']},
        {'word': 'meteorologist', 'pos': 'noun', 'meaning': 'A scientist who studies the weather.',
         'sentence': 'The meteorologist predicted snow for the weekend.',
         'synonyms': ['weather forecaster'], 'antonyms': []},
        {'word': 'heatwave', 'pos': 'noun', 'meaning': 'A long period of unusually hot weather.',
         'sentence': 'The heatwave lasted for ten days.',
         'synonyms': [], 'antonyms': []},
        {'word': 'flood', 'pos': 'noun', 'meaning': 'A large amount of water covering land that is usually dry.',
         'sentence': 'The flood covered the fields.',
         'synonyms': ['deluge'], 'antonyms': ['drought']},
        {'word': 'barometer', 'pos': 'noun', 'meaning': 'An instrument that measures air pressure to help forecast the weather.',
         'sentence': 'The barometer showed that a storm was coming.',
         'synonyms': [], 'antonyms': []},
    ]},
    {'week': 13, 'theme': 'Friendship and Emotions', 'words': [
        {'word': 'empathy', 'pos': 'noun', 'meaning': 'The ability to understand how another person feels.',
         'sentence': 'She showed empathy by listening to her friend.',
         'synonyms': ['understanding'], 'antonyms': ['apathy']},
        {'word': 'loyalty', 'pos': 'noun', 'meaning': 'Staying faithful and supportive to a person or group.',
         'sentence': 'Their loyalty to each other never wavered.',
         'synonyms': ['faithfulness'], 'antonyms': ['betrayal']},
        {'word': 'reassure', 'pos': 'verb', 'meaning': 'To say or do something to take away someone\'s worries.',
         'sentence': 'The nurse tried to reassure the nervous child.',
         'synonyms': ['comfort'], 'antonyms': ['worry']},
        {'word': 'sympathy', 'pos': 'noun', 'meaning': 'A feeling of sorrow for someone else\'s trouble.',
         'sentence': 'We sent a card with our sympathy.',
         'synonyms': ['compassion'], 'antonyms': ['indifference']},
        {'word': 'jealous', 'pos': 'adjective', 'meaning': 'Unhappy because you want what someone else has.',
         'sentence': 'He felt jealous of his friend\'s new bike.',
         'synonyms': ['envious'], 'antonyms': ['content']},
        {'word': 'resentment', 'pos': 'noun', 'meaning': 'A feeling of bitterness about something that seems unfair.',
         'sentence': 'She tried not to let resentment spoil their friendship.',
         'synonyms': ['bitterness'], 'antonyms': ['goodwill']},
        {'word': 'nostalgic', 'pos': 'adjective', 'meaning': 'Feeling a happy longing for the past.',
         'sentence': 'Looking at old photos made her feel nostalgic.',
         'synonyms': ['sentimental'], 'antonyms': []},
        {'word': 'vulnerable', 'pos': 'adjective', 'meaning': 'Easily hurt in body or feelings.',
         'sentence': 'Starting a new school can make you feel vulnerable.',
         'synonyms': ['exposed'], 'antonyms': ['protected', 'strong']},
        {'word': 'confide', 'pos': 'verb', 'meaning': 'To tell someone a secret because you trust them.',
         'sentence': 'She likes to confide in her best friend.',
         'synonyms': ['share', 'trust'], 'antonyms': []},
        {'word': 'companion', 'pos': 'noun', 'meaning': 'A person who spends time with you.',
         'sentence': 'The dog was her loyal companion on every walk.',
         'synonyms': ['friend', 'partner'], 'antonyms': []},
    ]},
    {'week': 14, 'theme': 'Space Exploration', 'words': [
        {'word': 'satellite', 'pos': 'noun', 'meaning': 'An object that travels around a planet in space.',
         'sentence': 'The satellite sends weather pictures to Earth.',
         'synonyms': [], 'antonyms': []},
        {'word': 'mission', 'pos': 'noun', 'meaning': 'A special job or task, especially in space.',
         'sentence': 'The mission to Mars will take many months.',
         'synonyms': ['task', 'assignment'], 'antonyms': []},
        {'word': 'probe', 'pos': 'noun', 'meaning': 'An unmanned spacecraft sent to explore space.',
         'sentence': 'The probe sent back photos of Jupiter.',
         'synonyms': [], 'antonyms': []},
        {'word': 'module', 'pos': 'noun', 'meaning': 'A separate part of a spacecraft or space station.',
         'sentence': 'The astronauts entered the living module.',
         'synonyms': ['section', 'unit'], 'antonyms': []},
        {'word': 'lunar', 'pos': 'adjective', 'meaning': 'Relating to the Moon.',
         'sentence': 'The lunar surface is covered in dust and craters.',
         'synonyms': [], 'antonyms': []},
        {'word': 'cosmos', 'pos': 'noun', 'meaning': 'The universe, thought of as an ordered whole.',
         'sentence': 'She loved to read about the cosmos.',
         'synonyms': ['universe', 'space'], 'antonyms': []},
        {'word': 'constellation', 'pos': 'noun', 'meaning': 'A group of stars that forms a pattern in the sky.',
         'sentence': 'Orion is a famous constellation.',
         'synonyms': [], 'antonyms': []},
        {'word': 'rover', 'pos': 'noun', 'meaning': 'A vehicle that explores the surface of a planet or moon.',
         'sentence': 'The rover rolled across the red dust.',
         'synonyms': [], 'antonyms': []},
        {'word': 'launch', 'pos': 'verb', 'meaning': 'To send a rocket or spacecraft into the air.',
         'sentence': 'They will launch the rocket at dawn.',
         'synonyms': ['blast off', 'send'], 'antonyms': ['land']},
        {'word': 'exoplanet', 'pos': 'noun', 'meaning': 'A planet that orbits a star other than our Sun.',
         'sentence': 'Astronomers discovered a new exoplanet this year.',
         'synonyms': [], 'antonyms': []},
    ]},
    {'week': 15, 'theme': 'Fantasy and Imagination', 'words': [
        {'word': 'fantasy', 'pos': 'noun', 'meaning': 'A story full of magic and imaginary things.',
         'sentence': 'She wrote a fantasy about a flying castle.',
         'synonyms': ['fiction', 'daydream'], 'antonyms': ['reality']},
        {'word': 'mythical', 'pos': 'adjective', 'meaning': 'Existing only in stories or ancient legends.',
         'sentence': 'The unicorn is a mythical creature.',
         'synonyms': ['legendary', 'imaginary'], 'antonyms': ['real']},
        {'word': 'imaginary', 'pos': 'adjective', 'meaning': 'Existing only in the mind, not real.',
         'sentence': 'His imaginary friend was a talking giraffe.',
         'synonyms': ['unreal', 'invented'], 'antonyms': ['real']},
        {'word': 'enchanted', 'pos': 'adjective', 'meaning': 'Under a magic spell.',
         'sentence': 'The enchanted garden glittered in the moonlight.',
         'synonyms': ['magical', 'bewitched'], 'antonyms': ['ordinary']},
        {'word': 'sorcerer', 'pos': 'noun', 'meaning': 'A person in stories who uses magic.',
         'sentence': 'The sorcerer made the stars dance.',
         'synonyms': ['wizard', 'magician'], 'antonyms': []},
        {'word': 'realm', 'pos': 'noun', 'meaning': 'A kingdom or a world in a story.',
         'sentence': 'The knight travelled to a distant realm.',
         'synonyms': ['kingdom', 'domain'], 'antonyms': []},
        {'word': 'fable', 'pos': 'noun', 'meaning': 'A short story that teaches a lesson, often with animals.',
         'sentence': 'The fable of the tortoise and the hare teaches patience.',
         'synonyms': ['parable', 'tale'], 'antonyms': []},
        {'word': 'whimsical', 'pos': 'adjective', 'meaning': 'Playful, unusual and full of imagination.',
         'sentence': 'The artist drew whimsical animals in hats.',
         'synonyms': ['quirky', 'playful'], 'antonyms': ['serious']},
        {'word': 'illusion', 'pos': 'noun', 'meaning': 'Something that looks real but is not.',
         'sentence': 'The magician created the illusion of floating.',
         'synonyms': ['trick', 'deception'], 'antonyms': ['reality']},
        {'word': 'creature', 'pos': 'noun', 'meaning': 'A living being, especially an imaginary one.',
         'sentence': 'A gentle creature lived in the cave.',
         'synonyms': ['being', 'animal'], 'antonyms': []},
    ]},
    {'week': 16, 'theme': 'Healthy Living', 'words': [
        {'word': 'nutrition', 'pos': 'noun', 'meaning': 'The food that a body needs to grow and stay healthy.',
         'sentence': 'Good nutrition helps you concentrate at school.',
         'synonyms': ['nourishment'], 'antonyms': []},
        {'word': 'hydrate', 'pos': 'verb', 'meaning': 'To drink enough water so that your body works well.',
         'sentence': 'You must hydrate during a long run.',
         'synonyms': [], 'antonyms': ['dehydrate']},
        {'word': 'balanced', 'pos': 'adjective', 'meaning': 'Having the right mix of different things.',
         'sentence': 'A balanced diet includes fruit, vegetables and protein.',
         'synonyms': ['even', 'proportioned'], 'antonyms': []},
        {'word': 'metabolism', 'pos': 'noun', 'meaning': 'The process by which your body turns food into energy.',
         'sentence': 'Exercise can speed up your metabolism.',
         'synonyms': [], 'antonyms': []},
        {'word': 'sedentary', 'pos': 'adjective', 'meaning': 'Involving a lot of sitting and not much movement.',
         'sentence': 'A sedentary lifestyle can make you feel tired.',
         'synonyms': ['inactive'], 'antonyms': ['active']},
        {'word': 'mindfulness', 'pos': 'noun', 'meaning': 'Paying calm, careful attention to the present moment.',
         'sentence': 'Mindfulness can help you relax before a test.',
         'synonyms': ['awareness'], 'antonyms': []},
        {'word': 'protein', 'pos': 'noun', 'meaning': 'A substance in foods like eggs and beans that helps your body grow and repair itself.',
         'sentence': 'Eggs are a good source of protein.',
         'synonyms': [], 'antonyms': []},
        {'word': 'wellbeing', 'pos': 'noun', 'meaning': 'The state of being comfortable, healthy and happy.',
         'sentence': 'Sleep is important for your wellbeing.',
         'synonyms': ['health', 'welfare'], 'antonyms': []},
        {'word': 'posture', 'pos': 'noun', 'meaning': 'The way you hold your body when sitting or standing.',
         'sentence': 'Good posture is good for your back.',
         'synonyms': ['stance', 'position'], 'antonyms': []},
        {'word': 'stamina', 'pos': 'noun', 'meaning': 'The strength to keep going for a long time.',
         'sentence': 'Cross-country running builds stamina.',
         'synonyms': ['endurance'], 'antonyms': ['weakness']},
    ]},
    {'week': 17, 'theme': 'Buildings and Cities', 'words': [
        {'word': 'architect', 'pos': 'noun', 'meaning': 'A person who designs buildings.',
         'sentence': 'The architect sketched a plan for the new library.',
         'synonyms': ['designer'], 'antonyms': []},
        {'word': 'foundation', 'pos': 'noun', 'meaning': 'The solid base on which a building stands.',
         'sentence': 'The foundation must be strong to hold the walls.',
         'synonyms': ['base', 'groundwork'], 'antonyms': []},
        {'word': 'skyscraper', 'pos': 'noun', 'meaning': 'A very tall building with many floors.',
         'sentence': 'The skyscraper has more than a hundred floors.',
         'synonyms': ['tower'], 'antonyms': []},
        {'word': 'infrastructure', 'pos': 'noun', 'meaning': 'The basic systems a city needs, such as roads and water supply.',
         'sentence': 'Good infrastructure keeps a city running smoothly.',
         'synonyms': [], 'antonyms': []},
        {'word': 'urban', 'pos': 'adjective', 'meaning': 'Relating to a town or city.',
         'sentence': 'Urban areas have more traffic than the countryside.',
         'synonyms': ['city'], 'antonyms': ['rural']},
        {'word': 'suburb', 'pos': 'noun', 'meaning': 'An area of houses on the edge of a city.',
         'sentence': 'We live in a quiet suburb.',
         'synonyms': [], 'antonyms': []},
        {'word': 'renovate', 'pos': 'verb', 'meaning': 'To repair and improve an old building.',
         'sentence': 'They plan to renovate the old cinema.',
         'synonyms': ['restore', 'refurbish'], 'antonyms': []},
        {'word': 'monument', 'pos': 'noun', 'meaning': 'A statue or building made to remember a person or event.',
         'sentence': 'The monument honours the town\'s founder.',
         'synonyms': ['memorial'], 'antonyms': []},
        {'word': 'landmark', 'pos': 'noun', 'meaning': 'A well-known building or feature that helps you recognise a place.',
         'sentence': 'The clock tower is a famous landmark.',
         'synonyms': [], 'antonyms': []},
        {'word': 'scaffolding', 'pos': 'noun', 'meaning': 'A framework of poles and planks used by builders.',
         'sentence': 'Scaffolding covered the front of the old school.',
         'synonyms': [], 'antonyms': []},
    ]},
    {'week': 18, 'theme': 'Oceans and Rivers', 'words': [
        {'word': 'tributary', 'pos': 'noun', 'meaning': 'A small river that flows into a larger one.',
         'sentence': 'Each tributary adds more water to the main river.',
         'synonyms': [], 'antonyms': []},
        {'word': 'estuary', 'pos': 'noun', 'meaning': 'The wide mouth of a river where it meets the sea.',
         'sentence': 'Birds feed on the mud in the estuary.',
         'synonyms': [], 'antonyms': []},
        {'word': 'delta', 'pos': 'noun', 'meaning': 'A flat area of land formed where a river splits as it meets the sea.',
         'sentence': 'The river formed a delta as it reached the sea.',
         'synonyms': [], 'antonyms': []},
        {'word': 'meander', 'pos': 'verb', 'meaning': 'To follow a winding path.',
         'sentence': 'The river will meander through the valley.',
         'synonyms': ['wind', 'wander'], 'antonyms': []},
        {'word': 'plankton', 'pos': 'noun', 'meaning': 'Tiny living things that drift in the sea.',
         'sentence': 'Whales feed on plankton.',
         'synonyms': [], 'antonyms': []},
        {'word': 'basin', 'pos': 'noun', 'meaning': 'An area of land that is drained by a river.',
         'sentence': 'The Amazon basin is very large.',
         'synonyms': [], 'antonyms': []},
        {'word': 'reef', 'pos': 'noun', 'meaning': 'A ridge of coral or rock near the surface of the sea.',
         'sentence': 'Colourful fish swim around the reef.',
         'synonyms': [], 'antonyms': []},
        {'word': 'tide', 'pos': 'noun', 'meaning': 'The rise and fall of the sea level twice a day.',
         'sentence': 'The tide covers the beach each evening.',
         'synonyms': [], 'antonyms': []},
        {'word': 'salinity', 'pos': 'noun', 'meaning': 'How salty something is.',
         'sentence': 'The salinity of the sea is higher than that of a lake.',
         'synonyms': ['saltiness'], 'antonyms': []},
        {'word': 'current', 'pos': 'noun', 'meaning': 'A steady flow of water in a particular direction.',
         'sentence': 'The current in the river was swift.',
         'synonyms': ['flow'], 'antonyms': []},
    ]},
    {'week': 19, 'theme': 'Courage and Heroes', 'words': [
        {'word': 'bravery', 'pos': 'noun', 'meaning': 'Courage in a difficult or frightening situation.',
         'sentence': 'The firefighter was awarded a medal for her bravery.',
         'synonyms': ['courage', 'valour'], 'antonyms': ['cowardice']},
        {'word': 'valiant', 'pos': 'adjective', 'meaning': 'Showing great courage.',
         'sentence': 'The valiant lifeboat crew set out in the storm.',
         'synonyms': ['brave', 'heroic'], 'antonyms': ['cowardly']},
        {'word': 'fearless', 'pos': 'adjective', 'meaning': 'Not afraid of anything.',
         'sentence': 'The fearless explorer climbed the peak.',
         'synonyms': ['bold', 'daring'], 'antonyms': ['timid']},
        {'word': 'selfless', 'pos': 'adjective', 'meaning': 'Caring more about others than about yourself.',
         'sentence': 'It was a selfless act to give up his seat.',
         'synonyms': ['unselfish', 'generous'], 'antonyms': ['selfish']},
        {'word': 'determination', 'pos': 'noun', 'meaning': 'A firm decision to keep trying until you succeed.',
         'sentence': 'With great determination, she finished the race.',
         'synonyms': ['resolve', 'persistence'], 'antonyms': ['doubt']},
        {'word': 'perseverance', 'pos': 'noun', 'meaning': 'Continuing to try despite difficulty.',
         'sentence': 'Perseverance helped him master the violin.',
         'synonyms': ['persistence', 'tenacity'], 'antonyms': ['giving up']},
        {'word': 'rescue', 'pos': 'verb', 'meaning': 'To save someone from danger.',
         'sentence': 'The lifeguard will rescue the swimmer.',
         'synonyms': ['save', 'free'], 'antonyms': ['abandon']},
        {'word': 'courageous', 'pos': 'adjective', 'meaning': 'Having the courage to face danger or difficulty.',
         'sentence': 'The courageous girl spoke up for her friend.',
         'synonyms': ['brave', 'bold'], 'antonyms': ['cowardly']},
        {'word': 'noble', 'pos': 'adjective', 'meaning': 'Having fine moral qualities such as honesty and bravery.',
         'sentence': 'The noble king helped his people.',
         'synonyms': ['honourable', 'worthy'], 'antonyms': ['dishonourable']},
        {'word': 'triumph', 'pos': 'noun', 'meaning': 'A great victory or success.',
         'sentence': 'Winning the cup was a triumph for the team.',
         'synonyms': ['victory', 'success'], 'antonyms': ['defeat']},
    ]},
    {'week': 20, 'theme': 'Persuasive Writing', 'words': [
        {'word': 'persuasive', 'pos': 'adjective', 'meaning': 'Good at making people do or believe something.',
         'sentence': 'She wrote a persuasive letter to the head teacher.',
         'synonyms': ['convincing'], 'antonyms': ['unconvincing']},
        {'word': 'emotive', 'pos': 'adjective', 'meaning': 'Causing strong feelings.',
         'sentence': 'The emotive poster made people want to donate.',
         'synonyms': ['moving', 'touching'], 'antonyms': []},
        {'word': 'exaggerate', 'pos': 'verb', 'meaning': 'To describe something as bigger or better than it really is.',
         'sentence': 'Do not exaggerate when you write an advert.',
         'synonyms': ['overstate'], 'antonyms': ['understate']},
        {'word': 'slogan', 'pos': 'noun', 'meaning': 'A short, catchy phrase used in advertising.',
         'sentence': 'The shop\'s slogan is easy to remember.',
         'synonyms': ['catchphrase'], 'antonyms': []},
        {'word': 'audience', 'pos': 'noun', 'meaning': 'The people who read, watch or listen to something.',
         'sentence': 'Think about your audience before you start writing.',
         'synonyms': ['readers', 'listeners'], 'antonyms': []},
        {'word': 'convincing', 'pos': 'adjective', 'meaning': 'Able to make you believe that something is true.',
         'sentence': 'His convincing speech won the vote.',
         'synonyms': ['persuasive'], 'antonyms': ['doubtful']},
        {'word': 'urgent', 'pos': 'adjective', 'meaning': 'Needing action straight away.',
         'sentence': 'The poster made an urgent plea for help.',
         'synonyms': ['pressing'], 'antonyms': ['unimportant']},
        {'word': 'rhetorical', 'pos': 'adjective', 'meaning': 'Used for effect rather than needing an answer, like a question.',
         'sentence': 'A rhetorical question makes the reader think.',
         'synonyms': [], 'antonyms': []},
        {'word': 'imperative', 'pos': 'adjective', 'meaning': 'Giving an order or command.',
         'sentence': '"Join us today" is an imperative sentence.',
         'synonyms': [], 'antonyms': []},
        {'word': 'appeal', 'pos': 'noun', 'meaning': 'A serious request for help or support.',
         'sentence': 'The charity made an appeal for winter coats.',
         'synonyms': ['plea', 'request'], 'antonyms': []},
    ]},
]
